### ISSUE TITLE
Python3 can't find packages installed via pip

### ISSUE THREAD

**Issue by JackPickering** [extrabacon/python-shell#105]
I have a python package which is used to sign an address with ecdsa, it uses various packages installed via pip which reside in lib/Python3/site-packages folder. 

When I run this in my python3 virtual environment, the files work correctly.

However, when I run the files using the python-shell, I get the error:

`ModuleNotFoundError: No module named 'eth_utils'`

This must be an import problem not finding the correct packages directory, as this import statement is in a file that is derived from the one I call i.e.

## file 1
------------------
from sign import sign

## Sign.py (same directory as file1)
-------------------
from eth_utils import get_data

This means that the import statement from file 1 is processed correctly as it finds sign.py, but how do I specify to sign.py to look into site-packages for the remaining modules?

**Comment by Jacobth** [comment]
I have this problem as well with Keras. How do I tell python-shell where my imports are?

**Comment by xocialize** [comment]
This is still an issue.  I'm running into an issue where running from the command line works great but I'm failing on importing form this:

No module named 'vgg'

from this line in the file: import transform, numpy as np, vgg, pdb, os

**Comment by Almenon** [comment]
Python-shell doesn't do any import magic which would be causing this problem, as long as your file is in the right location relative to the package being importee and you are using the right python path then it should work.

**Comment by filipppp** [comment]
Also not working for me!

**Comment by Almenon** [comment]
@filipppp how are you using python-shell?

My [Arepl-backend](https://github.com/Almenon/AREPL-backend/blob/master/index.ts) repo is working, if you copy the style there maybe it will start working for you.

**Comment by filipppp** [comment]
@Almenon Found the error! Wasn't the library at all! There was a mysterious folder called __pycache__ which killed the connections to the modules so that's why I couldn't import them.

**Comment by filipppp** [comment]
@Almenon Only my own installed modules didn't load. Don't know why.

**Comment by Almenon** [comment]
Closing - not a problem with python-shell.
