### ISSUE TITLE
Superuser at Python-shell

### ISSUE THREAD

**Issue by nickBukh** [extrabacon/python-shell#11]
Is it possible to run script with superuser privileges?
Like: 
exec("sudo python some_script.py", function (error, stdout, stderr) {
        //do smth;
    });

Can i run script above using your python-shell?

**Comment by extrabacon** [comment]
Not at the moment. The module spawns `python` as a child process. For sudo privileges, we need to spawn a `sudo` process, maybe with something like https://www.npmjs.com/package/sudo.

This should be a straightforward modification, pull requests are welcome!

**Comment by nickBukh** [comment]
Ok, thanks!
