### ISSUE TITLE
ModuleNotFoundError issue when using pyenv

### ISSUE THREAD

**Issue by maziarz** [extrabacon/python-shell#114]
I am not sure if this is in any way related to `pyenv`, but i am working in a global python version, namely 3.6.0 but i am not able to import a module which is functioning in the Python console.

This is the exception i get from my electron application:

`Uncaught Error: ModuleNotFoundError: No module named 'python_library.test'`

If i try to import this via shell theres no issues:

```
python
Python 3.6.0 (default, Nov 25 2017, 16:11:24)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_library.test
>>>
```

The module is installed through pip and should be globally accessible.

**Comment by Almenon** [comment]
can you paste the code you are using to invoke python-shell please?

**Comment by maziarz** [comment]
```
     PythonShell.run('test.py', { scriptPath: '/Users/testuser/Sandbox/scripts/' }, function (err, results) {
        if (err) throw err
        console.log(results)
      })
```

The source code:

```
import sys
from import python_library.test

```

**Comment by Almenon** [comment]
Can you run the following through python-shell?

```python
import sys
import os
print("version: " + sys.version + " current dir: " + os.getcwd() + " python location: " + sys.executable)
```

**Comment by maziarz** [comment]
```
GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] 
current dir: /Users/testuser/Sandbox/electron-vue-project/test-gui 
python location: /Users/testuser/.pyenv/versions/3.6.0/bin/python
```

**Comment by maziarz** [comment]
I did it through python shell as well, the `version` and `python location` are the same

**Comment by maziarz** [comment]
After much debugging the issue was related to the module itself and not python-shell. Closing the issue!

**Comment by Almenon** [comment]
I'm glad you found the problem :)

What was the issue, by the way?

**Comment by maziarz** [comment]
@Almenon the module was not properly installed in site-packages. When i was doing the python shell test in terminal i was inside the uninstalled module folder so i got a false positive. `python-shell` was doing exactly what it should with my global pyenv python.
