### ISSUE TITLE
Python-shell returns undefined with ParseError

### ISSUE THREAD

**Issue by phenric** [extrabacon/python-shell#115]
Hi,
When I run my script in my node project, it returns a ParseError without any other result than "undefined".

The exact error is :

> { Error: /usr/local/lib/python3.6/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
 > at PythonShell.parseError (/Users/path/node_modules/python-shell/index.js:191:17)
    at terminateIfNeeded (/Users/path/node_modules/python-shell/index.js:98:28)
    at ChildProcess.<anonymous> (/Users/path/node_modules/python-shell/index.js:89:9)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
 > executable: '/usr/local/Cellar/python/3.6.4_4/bin/python3',
  options: [ '-u' ],
  script: 'python/recommander.py',
  args: [ 2, [ 2 ] ],
  exitCode: 0 }

Is it possible that the error is returned due the userwarning even if when I run the script directly in the console with python, the userwarning does not affect the result ?

Thank you

**Comment by Almenon** [comment]
Can you post your python code please? And the code you used to call python-shell?

**Comment by Almenon** [comment]
No response - closing.
