### ISSUE TITLE
[pythception] : Run a python script inside another with python-shell

### ISSUE THREAD

**Issue by phenric** [extrabacon/python-shell#117]
Hi,

Firstly, thank you for the job. It's great and very helpful !

In my node project, I use python-shell to run a python script which runs another one. I call the second one with `from mymodule import myfunction`. But I strongly suspect due the error 

>  Error: TypeError: 'NoneType' object is not subscriptable

that my second script is never called.

Am I right ? How could I resolve that ? How can I be sure to call the second script with the first in python-shell ?

Thx for your help

**Comment by Almenon** [comment]
please give the context of the error - what is the code where the error happened? How are you calling python-shell?

**Comment by Almenon** [comment]
No response - closing.  Probably a error in the python code anyways.
