### ISSUE TITLE
How to handle error when python's path is invalid?

### ISSUE THREAD

**Issue by itsdax** [extrabacon/python-shell#118]
```javascript
            const PythonShell = require('python-shell');
            const options = {
                pythonPath: './notthepythonpath',
                scriptPath: 'scriptdir',
                args: [0, 0, 400, 400, 1, store.get('outputPath')],
                mode: 'text',
            };
            let pyshell = new PythonShell('script.py', options);
            pyshell.on('error', (err) => {
                alert(err);
            });
```
I've tried the callback ,and tried on('error') but both doesn't seem to catch it.

**Comment by sejsingffdc** [comment]
I ran into the same problem. I believe the root cause is with this line in python-shell:
```js
this.childProcess = child_process_1.spawn(pythonPath, this.command, options);
```

the spawn() function can throw an exception if the path is invalid (see here https://github.com/nwjs/nw.js/issues/1623). It appears that spawn must have an error handler attached like this:

```js
spawn.on('error', function (err) {
    console.log('spawn error:', err);
});
```

**Comment by sejsingffdc** [comment]
This code is in PythonShell's constructor.

**Comment by snowtype** [comment]
According to the docs at https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options, the error handler should be set on the spawned subprocess itself, not on `spawn`:
> Example of checking for failed spawn:
> ```js
> const { spawn } = require('child_process');
> const subprocess = spawn('bad_command');
> 
> subprocess.on('error', (err) => {
>   console.log('Failed to start subprocess.');
> });
> ```
Just to be sure I just checked:
```
Node.js> child_process.spawn.on
undefined

```

**Comment by sejsingffdc** [comment]
Could it be OS dependent behavior? I'm on Mac.

**Comment by Almenon** [comment]
@sejsingffdc nah, I have windows and it does same thing.

I'll change the error event to also fire when the path is invalid.  

Once I finish promise support (#77) the the python process will be launched via a start method which will return or reject a promise based on whether it sucessfully launched the process.
