### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by dhruv4** [extrabacon/python-shell#12]
Hey! This is a really cool module! Nice work! 

How can I make it use Python 3 instead of Python 2?

Thanks!

**Comment by extrabacon** [comment]
Thank you!

Your environment is using the Python 2 binary as the default. Either change your env or point to the Python 3 binary like so:

```
var PythonShell = require('python-shell');

var options = { pythonPath: 'path/to/python3' };

PythonShell.run('my_script.py', options, function (err, results) {

});
```

**Comment by dhruv4** [comment]
That was very helpful, thanks!

**Comment by Drulac** [comment]
You don't have to precise the full path, you can just precise python3 : 
```js
var PythonShell = require('python-shell');

var options = { pythonPath: 'python3' };

PythonShell.run('my_script.py', options, function (err, results) {

});
```
