### ISSUE TITLE
Run time error- Cannot find module "child process"

### ISSUE THREAD

**Issue by ChathurangiShyalika** [extrabacon/python-shell#120]
I'm going to execute a python script through an Ionic 3 application in the button click event. I have used Python-shell in order to accomplish this task.
 
Below is my code snippet in 'home.ts'.

```
import { PythonShell } from 'python-shell';

 rundata(){
  PythonShell.run('C:/ChathuS/PycharmProjects/Profiling module new/Profiling module/data.py', function (err) {
    if (err) throw err;
    console.log('Executed data.py');
  });}
```

In the 'home.html', I use a button click event to call the above function as follows.

```
   <button ion-button (click)="rundata()" *ngIf="facebook.loggedIn">  
        <ion-icon name="logo-facebook"></ion-icon>  Analyse profile 
    </button>
```

This gives me following error in the browser. 
![error](https://user-images.githubusercontent.com/23356795/39392034-b74168da-4a62-11e8-9a52-56588881cf61.PNG)

How to solve this issue?

**Comment by SanjayVig** [comment]
It says you're missing a module in your node_modules directory. Best way is to reinstall all node_modules present in package.json file by typing "**npm i**" in the terminal where your package.json is present.

**Comment by Almenon** [comment]
no response from OP - closing

**Comment by k-ish0212** [comment]
`"browser": {
    "child_process": false,
    "fs": false,
    "os": false,
    "path": false
  }`
add above to package.json may fix this issue.
