### ISSUE TITLE
Call a specific python function from node

### ISSUE THREAD

**Issue by TecJon** [extrabacon/python-shell#121]
I'd like to call specific python functions from node. I have some logic (loading a huge file) which takes about 2 minutes. I would like to load it once and then call python functions from node so that the file is loaded only once.

```python
# load a huge file takes 2min
model = xyz.load(path)

# function using that model
def doSomething(id):
    # some logic using the model
    return model.get(id)
```

How can I repeatedly call `doSomething()` without loading the file each time?

**Comment by leoschet** [comment]
I'm doing something similar, and you can create a python wrapper for your code, which would run forever reading lines from stdin and recieve commands from node to execute specific methods. The idea is [here](https://stackoverflow.com/questions/50223084/continuously-exchange-data-using-python-shell)

**Comment by TecJon** [comment]
Works like a charm. Thank you @leoschet.
