### ISSUE TITLE
Get the output from Python shell execution to a variable and return a value. Use this value in a different file

### ISSUE THREAD

**Issue by gkvappium** [extrabacon/python-shell#124]
I have a scenario in my Typescript based framework wherein I call a python file which interacts with an interactive CLI and gets the output. I want to have this as a reusable component meaning, I want to call this function in a different file and assign the return value from the function to a variable which is needed for some validation. But the problem is I cannot get the result assigned to a variable. It says undefined. Is there a way to get the output of that block and use it globally? My code is something like this.

    var pythonscriptpath = 'test.py'; //This py file interacts with a CLI and gets the output from the command

    var pythonShell = require('python-shell');

    export class Commands {
          runCommand(){
                  return pythonShell.run(pythonscriptpath, function(err,result){
                  console.log(result[7]); //Prints the output from the 7th line which is my desired line              
        }
}
    I want to use this function in another file like,
    commands = new Commands();
    let text = commands.runCommand();

Doing this would result undefined. Is there any workaround for this?

**Comment by gkvappium** [comment]
@Almenon @extrabacon any inputs?

**Comment by Almenon** [comment]
Either use a promise or a call back to get the result.   When you return pythonshell.run you are not returning the result - the result goes to the lambda function you defined.  If u want to see an example of python-shell with typescript you can look at my arepl-backend repo

**Comment by gkvappium** [comment]
@Almenon ,

Are you referring to handleResult method from arepl backend repo? Can you let me know if this is the correct one. If so, how do I use it in the scenario mentioned above?
