### ISSUE TITLE
npm test fails after installing python-shell

### ISSUE THREAD

**Issue by bgailer** [extrabacon/python-shell#126]
Seems like we have some missing documentation
N:\book_manager>npm install python-shell
..various  error including, in essence, can't find package.json
I (incorrectly) assumed I could ignore that.
N:\book_manager>npm test 
npm ERR! path N:\book_manager\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall opene }
npm ERR! enoent ENOENT: no such file or directory, open 'N:\book_manager\package.json'

I created a package.json file, reran the install which only issued warnings, reran test

> @ test N:\book_manager
> echo 'Error: no test specified'

'Error: no test specified'

What am I missing here?

**Comment by Almenon** [comment]
That error means you don't have any tests specified in your package.json

For example, in our repo we have the following specified:

  >"scripts": {
    "test": "mocha -R spec",
    "appveyorTest": "mocha --ui tdd --reporter mocha-appveyor-reporter test/*.js"
  },
