### ISSUE TITLE
How do I pass a arguments into a process executing with python-shell?

### ISSUE THREAD

**Issue by komalpharate** [extrabacon/python-shell#127]
https://stackoverflow.com/questions/163542/python-how-do-i-pass-a-string-into-subprocess-popen-using-the-stdin-argument

Want to send arguments to already running python script from Nodejs

**Comment by Almenon** [comment]
python-shell does not support communication with already running scripts.  Though that would be a nice feature I suppose.  I'll raise a enhancement issue but it probably wont get done anytime soon.
