### ISSUE TITLE
TypeError: spawn is not a function

### ISSUE THREAD

**Issue by ankitakhatri** [extrabacon/python-shell#128]
I am trying to use python-shell in reactjs to run a simple HelloWorld.py script:

var PythonShell = require('python-shell');

PythonShell.run('HelloWorld.py', function (err) {
  if (err) throw err;
  console.log('finished');
});
The error is being thrown in my index.js: this.childProcess = spawn(pythonPath, this.command, options);

The entire stack trace:

_index.js:59 Uncaught TypeError: spawn is not a function
at new PythonShell (index.js:59)
at Object../src/App.js (App.js:7)
at __webpack_require__ (bootstrap e3bd67dbe9081e2af164:678)
at fn (bootstrap e3bd67dbe9081e2af164:88)
at Object../src/index.js (index.css?f255:26)
at __webpack_require__ (bootstrap e3bd67dbe9081e2af164:678)
at fn (bootstrap e3bd67dbe9081e2af164:88)
at Object.0 (registerServiceWorker.js:117)
at __webpack_require__ (bootstrap e3bd67dbe9081e2af164:678)
at bootstrap e3bd67dbe9081e2af164:724
at bootstrap e3bd67dbe9081e2af164:724

Other Notes: 

HelloWorld.py has only one line of code-- print("Hello World")
When I try to do console.log( require('child_process').spawn ), I get undefined.
I am using verision 0.5.0 of pythonshell.

**Comment by GiancarlosIO** [comment]
@ankitakhatri are you trying to run the script in a browser? python-shell need a node-like environment.
Spawn is a function node child_process

**Comment by jankarltommy** [comment]
I'm running into the same issue inside my ember.js app. So when you say browser, are you saying that I can't run this on my localhost (client)? Does it have to be running on a server?

**Comment by Almenon** [comment]
You can't choose python-shell in the browser. The only language you can use in the browser is Javascript.
