### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by wilcollins** [extrabacon/python-shell#13]
I am continuously getting this memory issue after executing consecutive scripts, even when ran synchronously

![image](https://cloud.githubusercontent.com/assets/1123609/9148216/67ae48fe-3d29-11e5-93e1-8afadc81d394.png)

**Comment by Almenon** [comment]
Sounds like you ran out of memory.  Were you able to fix it or is it still happening?

**Comment by Almenon** [comment]
no response - closing.
