### ISSUE TITLE
configure CI unit tests to auto-build

### ISSUE THREAD

**Issue by Almenon** [extrabacon/python-shell#136]
@brucedjones or @extrabacon, I don't have admin access, so can someone go into webhooks and add appveyor please?

I'm planning on a series of commits for #134, #130, and possibly #111 and #135 and auto-builds would be nice to have.

Payload url: <wrong url, ignore.  See comment>
Content type: urlencoded
Enable SSL verification
Pushes and pull requests for triggering
Check active

**Comment by Almenon** [comment]
the right payload url is https://ci.appveyor.com/api/github/webhook?id=5rpd3xay4f802khc

**Comment by extrabacon** [comment]
Webhook added
