### ISSUE TITLE
Error: cv2.error: OpenCV (python shell+node js)

### ISSUE THREAD

**Issue by reinaldo28** [extrabacon/python-shell#137]
this is my node js script "https://pastebin.com/raw/k4E0KXry"
and this is my python script "https://pastebin.com/raw/u35sXYWa"

and when i start it with node js , error show up like this 
![z](https://user-images.githubusercontent.com/40595865/43876747-aed93f10-9bc0-11e8-848f-7f7139b66db2.png)

any solution for this error ?

**Comment by Almenon** [comment]
As you can see by the python traceback, this is a error in your python code, and not in python-shell.  If you want python help I suggest going on https://reddit.com/r/learnpython or the python discord.
