### ISSUE TITLE
Default script path should be written in documentation

### ISSUE THREAD

**Issue by Gtskk** [extrabacon/python-shell#14]
When I installed the module, I have the following error:
![image](https://cloud.githubusercontent.com/assets/2942038/9352662/9da1fc24-4695-11e5-88f8-3674b7b309a7.png)

I think you should tell that: the default script path is in "python" directory.

**Comment by hallfox** [comment]
I have to agree. We spent about half an hour trying to fix this problem and even with the documentation updated it still wasn't clear that the PyShell object uses a default scripts directory.

**Comment by BlakeBrown** [comment]
I would actually go so far as to say that there shouldn't be a default script path.

Most users would expect the default path to be their home directory.

**Comment by extrabacon** [comment]
The default script path is now the CWD. Published as 0.2.0.
