### ISSUE TITLE
pyhon-shell is undefined

### ISSUE THREAD

**Issue by baristaGeek** [extrabacon/python-shell#140]
In my package.json I have:

"python-shell": "^0.5.0",

which I added via Yarn. 

The important parts of my template look like this:

```
<button v-on:click='callPy'>Call py</button>
...
import {PythonShell} from 'python-shell';
...
    callPy () {
      // run a simple script
      PythonShell.run('script.py', function (err, results) {
        // script finished
      });
    }
```

And I'm getting Uncaught TypeError: Cannot read property 'run' of undefined

**Comment by Almenon** [comment]
Ah, right.  I just updated the readme to v1 but I don't have publish permissions so I havn't been able to publish v1 yet.  @brucedjones or @extrabacon, can I have publish permission please?

While I'm waiting for them to respond (it might be a while) I've downgraded the readme back to it's original status.

**Comment by Almenon** [comment]
So in answer to your question, take a look at the new (well, old) readme.  You will need to use require syntax to import python-shell untill v1 is released.

**Comment by baristaGeek** [comment]
Thanks @Almenon it seems to be (almost) working now. I'm trying to run 

```
PythonShell.run('hello.py', function (err) {
  if (err) throw err;
  console.log('finished');
});
```

and the console says  can't open file 'hello.py': [Errno 2] No such file or directory, despite having hello.py in the same directory than the file that contains the function above. 

Any clue?

**Comment by Almenon** [comment]
V1 just got released so if you update to that you can use typescript :)

Or old version still works fine too of course.
