### ISSUE TITLE
PythonShell is not a constructor

### ISSUE THREAD

**Issue by MongoExpUser** [extrabacon/python-shell#142]
The following code snippet is not working in version **1.0.1**
var PythonShell  = require('python-shell'); 
var pyshell = **new PythonShell('my_script.py');**

It gave the following error: "**PythonShell is not a constructor**"

Any solution to this?

**Comment by Almenon** [comment]
you're using require, but you should be using import.

See readme:

> import {PythonShell} from 'python-shell';

**Comment by MongoExpUser** [comment]
I tried the import statement, **import {PythonShell} from 'python-shell'**, but it still gives the same error.

Even if it works, does it that mean this version (1.0.1) will break existing pre-ES6 codes with the **required** statements. 

The required statements work in version 0.5.0 and below ...

**Comment by Almenon** [comment]
Worked for me in arepl-backend :/

https://github.com/Almenon/AREPL-backend/blob/master/index.ts

**Comment by Almenon** [comment]
Sorry about that - worked in my library so I assumed it would work in others.  

I included a declaration file - it should work for you now.

**Comment by MongoExpUser** [comment]
Thanks. The **require statement** is now working fine with the latest **python-shell** version (**1.0.2**).
