### ISSUE TITLE
Typescript strict mode, failing.

### ISSUE THREAD

**Issue by jordond** [extrabacon/python-shell#144]
`tsc` is failing to build my project that uses the latest `1.0.2` version of `python-shell`.

The `index.ts` was bundled with the compiled code, so `tsc` is pulling that in instead of the .js + types.  And the `index.ts` is failing the strict checks.

The `index.ts` should be added to your ignore file for npm

**Comment by Almenon** [comment]
Alright, let me do that.  In the meantime I think you can add this to your tsconfig to stop it from trying to compile python-shell:

    "exclude": [
        "node_modules"
    ]

**Comment by jordond** [comment]
I have that setting, doesn't work.  For the time being I added a `prebuild` script to delete the file.

**Comment by Almenon** [comment]
With that commit only the following files will be included:

    "*.d.ts",
    "*.js",
    "*.js.map",
    "CHANGELOG.md",
    "README.md"

Sound good?

**Comment by jordond** [comment]
Yes, that looks good.

**Comment by Almenon** [comment]
Alright, I released a new version (1.0.3)

**Comment by Almenon** [comment]
Did the new version work?

**Comment by jordond** [comment]
Sorry, yes it works now, thanks!
