### ISSUE TITLE
terminate a python pid

### ISSUE THREAD

**Issue by dezmaeth** [extrabacon/python-shell#15]
is there any way to get & kill a Python process already running?

**Comment by extrabacon** [comment]
The underlying child process is exposed as the `childProcess` property.

It is a standard Node.js ChildProcess instance.
https://nodejs.org/api/child_process.html#child_process_child_kill_signal

```js
var PythonShell = require('python-shell');
var pyshell = new PythonShell('my_script.py');
pyshell.childProcess.kill();
```

**Comment by dezmaeth** [comment]
perfect! thank you!
