### ISSUE TITLE
I am unable to run python-shell

### ISSUE THREAD

**Issue by lordbeerus0505** [extrabacon/python-shell#150]
var PythonShell = require('python-shell');
var pyshell = new PythonShell.run('test.py')
// get message back
pyshell.on('message', function (message) {
    // received a message sent from the Python script (a simple "print" statement) 
    console.log(message);
  });
  
  // end the input stream and allow the process to exit 
  pyshell.end(function (err) {
    if (err) throw err;
    console.log('exit');
  });

**ERRORS:**

var pyshell = new PythonShell.run('test.py')
              ^
TypeError: PythonShell.run is not a constructor

Instead if i use -
var pyshell = new PythonShell('test.py') I get the same error.

I am using Ubuntu 18.04 with npm 6.1.0 node version 10.4.0 and python 3.6 as default

**Comment by Almenon** [comment]
Run is a function, not a constructor.  You can only use new with constructors.

If you use var pyshell = new PythonShell('test.py') you should not be getting the same error. Can you double check what error you got please?

**Comment by Almenon** [comment]
also you are using require.  You should be using import as mentioned in the readme.

Reposting the relevant section of the readme:

### Running python code:

```typescript
import {PythonShell} from 'python-shell';

PythonShell.runString('x=1+1;print(x)', null, function (err) {
  if (err) throw err;
  console.log('finished');
});
```

If the script exits with a non-zero code, an error will be thrown.

Note the use of imports! If you're not using typescript ಠ_ಠ you can [still get imports to work with this guide](https://github.com/extrabacon/python-shell/issues/148#issuecomment-419120209).

**Comment by PetrovskYYY** [comment]
Also fixed this error with using `{PythonShell}` instead of `PythonShell`.

**Comment by christophermp** [comment]
Hi there!

Trying to run:
`import { PythonShell } from "python-shell";

PythonShell.run("my_script.py", null, function(err) {
  if (err) throw err;
  console.log("finished");
});`

But it gives me:

`C:\Users\XXX\Documents\Electronjs\electron-quick-start\src\macros.js:1
(function (exports, require, module, __filename, __dirname) { import { PythonShell } from "python-shell";
                                                                                                            ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
PS C:\Users\XXX\Documents\Electronjs\electron-quick-start\src>`

Somebody has an ide of why?

**Comment by christophermp** [comment]
Hi there! 

No i am not, i have just saved the code above inside the macros.js file.
Opend up powershell and executed command: node macros.js.

I have the Pytonshell installed in my modules folder.
