### ISSUE TITLE
How to package python-shell in Electron

### ISSUE THREAD

**Issue by spsvision** [extrabacon/python-shell#152]
I'm presently using python-shell to run python scripts from node.js. This is essentially being run on an electron.js app. When I package the app, python-shell works great, and the packaged .exe works fine. However, when I open the app in a computer without python installed, python-shell stops working. From research online, I found that I can convert my python scripts to .exe's to work on any computer. That said, I don't know how I can still use python-shell to facilitate communication from my javascript GUI to the python backend. Basically, my question is how can I utilize python-shell to work as I package my python scripts into an electron app.

I understand that this question may be confusing, but I'd be glad to further clarify and provide more context. I'd generally be grateful for any insight on the matter.

**Comment by Almenon** [comment]
This is exactly what I did in https://GitHub.com/almenon/AREPL

Looking at the code there should be helpful.

In my case I assumed the user already had python installed, however.  In your case... It gets a lot harder.  Either you need to get the user to install python or install it for them, or you need to package  it into a exe like you said.  If it is a exe then you miiight be able to still use python shell if you pass in a EMPTY python path so it executes the exe instead of trying to run python against the exe.

**Comment by chesucr** [comment]
https://github.com/bokeh/bokeh
Check this project, it combines multiple languages. But basically it is a python package. All the python code is in the `bokeh` folder and all the JavaScript is in the `bokehjs` folder (`package.json` is in there). To install a python package you need to create a `setup.py`, you can install all the files you need with this setup, they will be located in the `site-packages`. Actually they are using Typescript that compiles to JavaScript code, but the idea is what I said before

And now the part where I have doubts. I think you can publish the package somewhere, I do not know how. But if you want to make a simple standalone installer for a normal user maybe you can user "Advanced installer". In my case I am including a virtual environment in that installer where my package with all the python packages and dependencies (python executable included) and JavaScript (electron, python-shell, etc) are already included. 

Sometimes a virtual environment cannot be relocatable, depending on the application you install in it, they should use relative paths to make this work.

**Comment by Abhi0725** [comment]
@spsvision Did you found anything? I am stuck on the same.

**Comment by chesucr** [comment]
@Abhi0725 Check my project where I use an python environment to make `python-shell` work
https://github.com/ocean-data-qc/ocean-data-qc
First I set the [python path](https://github.com/ocean-data-qc/ocean-data-qc/blob/master/ocean_data_qc_js/src/js/renderer_modules/server_renderer.js#L324) that is inside the environment, and then I can already use `python-shell`

**Comment by Almenon** [comment]
@chesucr cool project, is it okay if I add it to the https://github.com/extrabacon/python-shell#used-by section?

**Comment by chesucr** [comment]
Sure @Almenon , feel free to do it :-)

**Comment by Jay1567** [comment]
> Sure @Almenon , feel free to do it :-)

Can you specify the steps you took to package your project into one standalone application. And the packages and settings you used to package the project.

**Comment by chesucr** [comment]
> Can you specify the steps you took to package your project into one standalone application. And the packages and settings you used to package the project.

Yes, I have used [`electron-builder`](https://www.electron.build/). Take a look at the `build` section in my `package.json` where I have used some attributes that are explained in the `electron-builder` website. I have set `asar=false` because I had some issues in the past, but the general recommendation is to use `asarUnpack` instead, if you need something outside the asar file.

Filnally, use yarn to create the standalone installer. I have added some shortcuts into the json file as well:

        "dist_mac": "electron-builder --macos",
        "dist_win": "electron-builder --win --x64",
        "dist_linux": "electron-builder --linux --x64"

**Comment by diptanu143** [comment]
I still need help with this.. Anyone has a workable solution to this problem.. It seems weird to force the users of my app to install Python !

**Comment by Almenon** [comment]
> It seems weird to force the users of my app to install Python 

Python is not included by default in windows, so you either have to tell users to install it manually, install it automatically, or ship your app with python.

**Comment by andredezzy** [comment]
Somebody found a way to automacally install/compile/package Python with the Electron app installer?

**Comment by Abhi0725** [comment]
@andredezzy I am using Pyinstaller for this and that is working fine.

**Comment by andredezzy** [comment]
@Abhi0725 Thanks!! I will try using it.

**Comment by ahmed4end** [comment]
@Abhi0725   who exactly did you do that ?

**Comment by Abhi0725** [comment]
@ahmed4end what do you mean by "not working fine"? What error are you getting? I would say better post that on Stackoverflow as it isn't issue with this package.

**Comment by LeonardoRick** [comment]
@Abhi0725 I think a common problem is that pyinstaller generates a .exe file. So how you're being able to run those files using `python-shell library`?

>  If it is a exe then you miiight be able to still use python shell if you pass in a EMPTY python path so it executes the exe instead of trying to run python against the exe
@Almenon  I know this is out of the project scope but when I pass a empty string  I receive an error that shows `py` as executable:

```
  at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  executable: 'py',
  options: [ '-u' ],
  script: 'C:\\Users\\leona\\iq\\iq-websocket\\python\\botR\\main.dist\\main.exe',
  args: [
    '--uid',
    'G0Z6YCH1EtWycrPuk43RKdv6UkJ3',
    '--botId',
    'aNJ5VEfgJEG84RcKuLynR',
    '--env',
    'local'
  ],
```
So it's not acctually trying to just execute the `.exe`. Is there a way to do that? I already tried to checkup a raw `child_process` but it would leave me with two different approaches to the same goal, just because now I want to use the `.exe` when it's delivered on user's machine

**Comment by Abhi0725** [comment]
@LeonardoRick to execute .exe you will need to use "child_process". I don't think python-shell has anything to do with that when you have already built the exe.

**Comment by LeonardoRick** [comment]
> If it is a exe then you miiight be able to still use python shell if you pass in a EMPTY python path so it executes the exe instead of trying to run python against the exe.

@Abhi0725 that's  what Almenon  said. 

It acctualy works and you should pass the `powershell.exe` path on `pythoPath` option.

**Comment by zbouslikhin** [comment]
> > If it is a exe then you miiight be able to still use python shell if you pass in a EMPTY python path so it executes the exe instead of trying to run python against the exe.
> 
> @Abhi0725 that's what Almenon said.
> 
> It actually works and you should pass the `powershell.exe` path on `pythoPath` option.

Hi, would you be able to provide an example of this? 
Thanks.

**Comment by LeonardoRick** [comment]
@zbouslikhin I have a class that implements options:
```python
import { Options } from 'python-shell';
export class PythonOptions implements Options {
```
Then I setpath and executable as that:
```python
this.pythonPath = 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe';
this.executable = 'start.bat';
```

and then I use 
```python
const pyOptions = new PythonOptions(...);
new PythonShell(pyOptions.executable, pyOptions);
```

What error you're receiving? Was my solution clear enough?

**Comment by zbouslikhin** [comment]
@LeonardoRick Thanks for the help!
Somewhat, It's still returning an error. Here's the code I'm using:
```
let options = {
            mode: 'json',
            pythonOptions: ['-u'],
            scriptPath: "D:\\dist",
            pythonPath: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'",
        };

        this.pyshell = new PythonShell('run.bat', options)
```
And the error returned is:
![image](https://user-images.githubusercontent.com/47977073/116558409-b31bc300-a8ff-11eb-848c-c68a0030cf4d.png)

**Comment by LeonardoRick** [comment]
Have you checked if your powershell is on acctually on this path? Maybe your windows is installed on `D:` so you would need to change it.

Just for the record, I don't remember if its needed but I'm also setting ` detached = false;`

**Comment by hassan-yosh** [comment]
@LeonardoRick what did u guys wrote in the start.bat file ? 
I'm trying to solve this in linux but i dont know what to put in this start.bat file !
thanx

**Comment by LeonardoRick** [comment]
> @LeonardoRick what did u guys write in the start.bat file ? 
> 
> I'm trying to solve this in linux but i dont know what to put in it and why do we need this file this start.bat file !
> 
> thanx

Hi, my problem was not exactly using it with electron. I just shown an option to execute a .exe or .bat using python-shell. What's inside your script is up to you

**Comment by pranavAtCamify** [comment]
Here's how I did it using pyInstaller so that we don't need python on the client machine - https://pranavjoglekarcodes.web.app/blogs/posts/2021/python_in_electron/
Open to suggestions and improvements.



PS: The solution doesn't include python-shell, cause I don't think it's required in this case, so let me know if the comment is against the rules. Will take it down.
