### ISSUE TITLE
exit code 2

### ISSUE THREAD

**Issue by DeaVenditama** [extrabacon/python-shell#153]
hi..
im using python-shell inside my electron app, when its in dev mode its running well with no problem.

but, when i packaged my electron app into production, 
its returned an error message "exit code: 2", which is error message from pyshell..

what is the meaning of 2 in exit code python shell?
where can i see the documentation about error code?

thank you,
--sorry for my poor english, this library is cool!!--

**Comment by DeaVenditama** [comment]
My guess is that I can't find the location of my python script. am i right?

**Comment by Almenon** [comment]
Probably so.  I would suggest looking at the AREPL repo on my profile to see how to call python shell correctly in electron.  In the code there I change my config based on dev/prod
