### ISSUE TITLE
json mode and run method

### ISSUE THREAD

**Issue by Olmer1st** [extrabacon/python-shell#16]
Is it possible to use PythonShell.run together with mode:JSON?
What is correct options structure?

**Comment by extrabacon** [comment]
Simply set options using the second argument, like so:
```js
PythonShell.run('script.py', { mode: 'json' });
```

**Comment by Olmer1st** [comment]
Yes.  Ok.  But how to transfer message?

**Comment by extrabacon** [comment]
Can you clarify your question? What are you struggling with exactly?

Basically, `run` will return an instance which you can use to send and receive messages.
```js
var python = PythonShell.run('script.py', { mode: 'json' });
// send a message
python.send({ hello: 'world' });
// receive a message from Python
python.on('message', function (message) {
  // handle message sent from Python
}
```

On the Python side, you simply read from stdin and write to stdout.

```python
// send a JSON message to node
print json.dumps(obj)
// receive messages
for message in sys.stdin:
  # handle message sent from node
```

**Comment by Olmer1st** [comment]
I want to use this example:
PythonShell.run('my_script.py', options, function (err, results) {
  if (err) throw err;
  // results is an array consisting of messages collected during execution
  console.log('results: %j', results);
});

this example work only with args.

**Comment by Almenon** [comment]
Still having trouble? If not I'll close this.
