### ISSUE TITLE
Uncaught SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by daslicht** [extrabacon/python-shell#162]
Hi,
when I run the following code in a blank Electron App 
```
import {PythonShell} from 'python-shell';

PythonShell.run('./my_py.py', null, function (err) {
  if (err) throw err;
  console.log('finished');
});
```
I get this:
![](https://i.imgur.com/KogHXDS.png)

Whats wrong / missing please?
~ Marc

**Comment by Almenon** [comment]
Can u post ur python code pls?

**Comment by daslicht** [comment]
I want to make make a GUI for this:
http://denivel.blogspot.com/2018/03/new-release-for-nimbank-tool-in-v2.html

**Comment by Almenon** [comment]
What versiom of node are you using?

Are you using typescript?

**Comment by daslicht** [comment]
node: v10.13.0
no typescript

maybe it is teh wrong path ?
```PythonShell.run('./my_py.py',```

**Comment by Almenon** [comment]
Nah a bad path would not result in a syntax error.

Either try using typescript (I would recommend this) or node's  --experimental-modules flag.

**Comment by daslicht** [comment]
How much would typescript help with taht simple code : 
```
import {PythonShell} from 'python-shell';

PythonShell.run('./my_py.py', null, function (err) {
  if (err) throw err;
  console.log('finished');
});
```
?

**Comment by Almenon** [comment]
You never know when you might add onto code.  Simple code can very quickly get complex.

But you don't have to use typescript, that's just what I recommend.  You could use the --experimental-modules flag

**Comment by daslicht** [comment]
ok solved, it was just the import statement
