### ISSUE TITLE
Error importing python-shell on windows 10

### ISSUE THREAD

**Issue by Gatunox** [extrabacon/python-shell#164]
On my windows 10, with node --version  v11.2.0 when i execute **import {PythonShell} from 'python-shell';** I get:

```
import {PythonShell} from 'python-shell';
       ^

SyntaxError: Unexpected token {
```

What's wrong?

Using **let {PythonShell} = require('python-shell')** Does work.

**Comment by Almenon** [comment]
Did you read this part of the readme?

> Note the use of imports! If you're not using typescript ಠ_ಠ you can still get imports to work with [this guide](https://github.com/extrabacon/python-shell/issues/148#issuecomment-419120209).

**Comment by Gatunox** [comment]
Ok, I'm not planning to install nor use TypeScript so I will disregard and close this.

**Comment by Almenon** [comment]
You don't have to use typescript, see the link I provided above:
> So if you want to use imports you have four options:
> 1) Use latest version of node with --experimental-modules flag. Node 8.5 might also work.
> 2) use [babel](https://timonweb.com/posts/how-to-enable-es6-imports-in-nodejs/)
> 3) use [esm](https://www.npmjs.com/package/esm)
> 4) use typescript (not applicable in your case)
