### ISSUE TITLE
Throwing errors on executing python script

### ISSUE THREAD

**Issue by jamesgeorge007** [extrabacon/python-shell#167]
Consider this NodeJS script
```js
PythonShell.run(file, null, (err, result) => {
  console.log(result.toString());
});
```
> Where file points to a valid python script

![capture](https://user-images.githubusercontent.com/25279263/50372079-95324b00-05ed-11e9-928d-efa2047996ed.JPG)

What is going wrong?

**Comment by Almenon** [comment]
What os do you have? Is python in your PATH?

**Comment by jamesgeorge007** [comment]
OS: `Windows 10 version 1809`
Python is available as `py` from the command prompt by default.

**Comment by jamesgeorge007** [comment]
@Almenon I think #168 resolves the issue.
