### ISSUE TITLE
Running as a module

### ISSUE THREAD

**Issue by teuteuguy** [extrabacon/python-shell#17]
Hi, 
I'm trying to create a module that uses python-shell, however I'm running into problems with referencing the python file I need to call.

I'm placing all the files into node_modules/test_module folder and in there, I've got a test_file.py and index.js.

Whatever I reference test_file.py with either directly or ./test_file.py, the application can't find the file. The only way is to reference it via the apps directory structure and in that case my module needs to refer to the file as: node_modules/test_module/test_file.py
Is there a better way to do this ?

Thanks

**Comment by extrabacon** [comment]
Have you tried concatenating with `__dirname`?
https://nodejs.org/docs/latest/api/globals.html#globals_dirname

**Comment by teuteuguy** [comment]
OK thanks for that information. However I still can't get it to work.

Here is an example of what I've done.

I have 3 files.
app.js
sensor/sensor.js
sensor/sensor.py

app.js
```
var sensor = require('./sensor/sensor');
sensor.get(function(err, result) {
  if (err) throw err;
  console.log(result);
});
```

sensor/sensor.js
```
var PythonShell = require('python-shell');
module.exports = {
  get: function(cb) {
    console.log(__dirname);
    PythonShell.run('/sensor/sensor.py', function(err, results) {
      if (err) cb(err, null);
      cb(err, JSON.parse(results[0]));
    });
  }
};
```
sensor/sensor.py : don't worry about this file for now.

Now, if in the call to PythonShell.run I use: '/sensor/sensor.py' it works.
If I use: __dirname + '/sensor.py' it does not, and I get: Error: process exited with code 2

**Comment by extrabacon** [comment]
I initially designed PythonShell for this exact purpose. I wanted to read Excel files with very good Python libraries (https://github.com/extrabacon/pyspreadsheet). I simply used `__dirname` to point to my script folder.

See an example here: https://github.com/extrabacon/pyspreadsheet/blob/master/index.js
In this example, I set the path for all instances, so I no longer have to worry about that later in my code.

One thing for sure, you should be able to refer to your script without absolute paths (with a leading slash).

Another thing to look for is the version of python-shell you are currently using. Version 0.2.0 recently changed the default path for scripts. The new path is '.', as opposed to './python'. From the example seen above, you did not set a script path, so this default value might impact your result.

**Comment by mix3d** [comment]
Is there a way to set the PWD / root folder for commands? For example, if I have a project root of `./`, a folder `./scripts/` where my python script lives, and another folder `./keys/` where some files I will be passing to my python script live (via args), I'd want the python module to run at the same level as the main node.js script, which is the project root. However, when passing project-root based urls as args to the python script, it could not find the files. 

Using `__dirname` works for now, but I'd prefer to set the root once in the options, or even have it work that way by default, since it seems what would be expected.

**Comment by The-Outrider** [comment]
Hey @teuteuguy had a similar issue. 

used the options variable to solve.

```
    var options = {
        mode: 'text',
        scriptPath: __dirname + '/pythonScripts',
        args: [

        ]
    };
    var pyshell = new PythonShell('calculator.py', options);
```
My folder layout looks like this.
- routes
-- pythonScripts
--- calculator.py
-- index.js

My implementation is a little different, but maybe this direction works for you.

**Comment by Almenon** [comment]
closing - looks like outrider offered a solution.
