### ISSUE TITLE
Stopping child process

### ISSUE THREAD

**Issue by extralaces** [extrabacon/python-shell#174]
Not really issue related, but within my script I am creating and starting a child process through a series of buttons, how would i go about stopping the child process through another button? is there a way i can create the child process and have it remain idle until i start it maybe? thanks.

**Comment by Almenon** [comment]
terminate() can kill the process.

https://github.com/extrabacon/python-shell/blob/master/index.ts#L406

**Comment by LeonardoRick** [comment]
the new terminate is a `.kill()`? its currently not working for me in windows
