### ISSUE TITLE
function extend "unexpected token"

### ISSUE THREAD

**Issue by sebastianet** [extrabacon/python-shell#177]
I am trying to use python from nodejs on a Raspberry.

*) Python version :

` $ python -V
Python 2.7.9
`

*) Node version :

`$ node -v
v5.12.0
`

It seems to me it is a problem with the node version, 
but this is the last one I see after "sudo apt-get update"

Any ideas ?

**Comment by sebastianet** [comment]
A very interesting point : in the same Raspberry, I have some python-shell code that does run properly.

The one running OK has ./node_modules/python-shell $ cat CHANGELOG.md -> 0.0.3
The one with the error has /node_modules/python-shell $ cat CHANGELOG.md -> 1.0.4

So .. what is the "node" requirements for "python-shell" version 1.0.4 ?

**Comment by Almenon** [comment]
At least Node 8.  I would recommend upgrading python version as well, although python 2 should work.

**Comment by Almenon** [comment]
Oh and preferably latest version of node of course

**Comment by sebastianet** [comment]
mr Almenon - when I run the command "sudo apt-get update" I understand I get the latest versions of all installed software as far as Raspberry supports them.
Am I right ?

So, going from node v5.12 to node v8 is not the line I'd like to take.

How can I install "phyton-shell" v 0.0.3 on my machine ?

**Comment by sebastianet** [comment]
Looks I forgot to display the error I receive.
It is

`/home/sag/express-sendfile/node_modules/python-shell/index.js:29
function extend(obj, ...args) {
                     ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
`

**Comment by sebastianet** [comment]
well, I am running a full upgrade with 

`sudo apt full-upgrade -y`

more news in10 minutes

**Comment by Almenon** [comment]
For installing a specific version: https://60devs.com/npm-install-specific-version.html

**Comment by Almenon** [comment]
I think you would want version 0.4.0 for node 5.

**Comment by sebastianet** [comment]
Thanks alot, mr Almenon. 

I have run "full upgrade" (sudo apt full-upgrade -y) and still node versio is "v5.12.0"
And still the same problem with "/python-shell/index.js:29"

So now I shall try to un-install "python-shell" and re-install it forcing version "0.4.0"

I do appreciate your support a lot. Thanks.

**Comment by sebastianet** [comment]
done - python-shell v0.4.0 called from node v5.12.0 runs correct

guess I shall go into node v11 in short future, when I read about what "ES6" is ...

thanks a lot.
