### ISSUE TITLE
Sending arguments.

### ISSUE THREAD

**Issue by alienbuild** [extrabacon/python-shell#182]
Great package and it seems to be working well. I just need some clarity on how to send arguments to the script. 

Ultimately I need to run:
`py -m scripts.label_image --graph=tf_files/retrained_graph.pb --image=tf_files/dogs/test.jpg` 

I've tried setting options with the args option containing the above arguments, but I don't think I'm doing it correctly. Any guidance appreciated.

    let options = {
        pythonOptions: ['-u'], // get print results in real-time
        scriptPath: './playground/tf_files/',
        args: ['--graph=playground/tf_files/retrained_graph.pb', '--image=playground/tf_files/dogs/test.jpg']
    };

    PythonShell.run('label_image.py', options, function (err, pyRes) {
        if (err) throw err;
        console.log('finished');
        console.log('results: %j', pyRes);
        res.send({ result: pyRes });
    });

**Comment by porterehunley** [comment]
For those who may be confused, OP needed to split up the flags and the values into separate arguments:

`args: ['--graph', 'playground/tf_files/retrained_graph.pb', '--image', 'playground/tf_files/dogs/test.jpg']`

This should probably be in the documentation.
