### ISSUE TITLE
Using python-shell with aniconda/miniconda

### ISSUE THREAD

**Issue by mashaalmemon** [extrabacon/python-shell#184]
Can you give an example of how python-shell might be used with Aniconda/miniconda environments?

**Comment by mashaalmemon** [comment]
Anyone maintaining this project?

**Comment by Almenon** [comment]
I'm still maintaining it, I'm just not very active. A lot of issues posted on here are just people having problems with python or python-shell configuration and thinking it's a issue with python-shell. I have a repo I do actively develop ([arepl](https://github.com/Almenon/AREPL-vscode)) so when python-shell is lacking something I need for arepl I add it in.

**Comment by Almenon** [comment]
and as for how python shell could be used with anaconda/miniconda, just pass in the path to the python executable. It doesn't matter how or where python is installed as long as you have the right path.

**Comment by Almenon** [comment]
```python
import os
import sys
os.path.dirname(sys.executable)
```

**Comment by mashaalmemon** [comment]
@Almenon got it.

**Comment by Almenon** [comment]
Actually might be more complex than that if you need to activate the environment.... I'll leave this issue open

**Comment by CallMeLaNN** [comment]
I'm currently using conda without any issue. To active the env, it has to be done in the cmd/shell before the node run.

Additionally to make it work in VSCode terminal, point `"python.pythonPath"` setting to python inside the env. You can close this issue.
