### ISSUE TITLE
Question - how to install packages using pip

### ISSUE THREAD

**Issue by MatthyPlayz** [extrabacon/python-shell#185]
I'm working on a project and it has a login system with Python and Node, but I need to install these packages for it to work:
flask
os
sqlalchemy
tabledef

But I don't know how to install these.

**Comment by jemmyv** [comment]
You need to create a virtual environment and map the python executable on the options parameter and install the required libraries using pip.
```

            let options = {
                mode: 'text',
                pythonPath: "path/to/your/python/exe",
                pythonOptions: ['-u'],
                // make sure you use an absolute path for scriptPath
                scriptPath: "path/to/your/scripts",
                args: [args]
            };
```

**Comment by MatthyPlayz** [comment]
Thanks!
