### ISSUE TITLE
Detecting wrong pythonPath

### ISSUE THREAD

**Issue by bbeaudry** [extrabacon/python-shell#188]
It seems like there is no way of testing if a pythonPath is valid. Ex:
```
let options = {
    pythonPath: "wrongPythonPath"
};

PythonShell.run("script.py", options, function (err) {
    // do stuff
});
```
where `wrongPythonPath` doesn't correspond to a valid python path. In this case, the `PythonShell.run(...)` would not be executed and no error would be thrown.

How could we validate a non-execution of the script because of an incorrect pythonPath?

**Comment by Almenon** [comment]
You would get an error if the python path is invalid.  It wouldn't say that specifically.  Are you accepting a dynamic python path or is it hardcoded?

**Comment by bbeaudry** [comment]
Thanks for your help. I'm accepting a dynamic python path. I also tried to put it in a try-catch and I didn't received an error.

**Comment by bbeaudry** [comment]
After some digging in the source code, the static function getVersion("my-python-path") returns a promise that fails if the python path is not valid. Ex:
`PythonShell.getVersion("wrongPath").then((data) => { // valid }).catch((e) => { // invalid });     
`

Closing issue.
