### ISSUE TITLE
Errors on message event listeners get incorrectly caught as incorrect message errors

### ISSUE THREAD

**Issue by ClimbsRocks** [extrabacon/python-shell#19]
Thanks for building out this tool! I use it all the time. 

One issue I've run into time and time again is that I will have a bug in some logic I've written that's dependent on a message event firing. 

The message event fires, my code has a bug in it, an error gets thrown; standard operating procedure. 

Except, python-shell catches the error, with a log saying that the message itself is broken. 

Needless to say, this makes it super difficult to track down the source of the bug! 

The obvious solution is to just emit the event, and let the standard error handling system take over from there, so it can give the user some good information about where the source of the error is. 

If you really want, you could add in a little warning in that error chain saying "This error might be caused by an invalid message from your python shell.", but still letting the rest of the error handling system take place. 

Again, thanks for the useful tool! I'd love to hear your thoughts on error handling. If my approach doesn't make sense for this module, let me know and I'll just operate off my own fork.

**Comment by extrabacon** [comment]
I will definitely take a look, thank you for the feedback!
