### ISSUE TITLE
How can I store the output of Python script to a variable?

### ISSUE THREAD

**Issue by OgulcanCelik** [extrabacon/python-shell#193]
```
let {PythonShell} = require('python-shell')
let path = require("path")
PythonShell.run(path.join(__dirname, "pyengine/view.py"), null, function (err,result) {
  if (err) throw err;
  console.log('finished');
  console.log(result)
});

```

So here, I can see the output of the Python script with "console.log(result)". I want to store this result which is coming from a Python script via print method, and use it on NodeJS part. Since this result is in .run's scope, how can I assign it to a variable?

It's not particularly about python-shell but I'll be really glad if someone could help me.

**Comment by MongoExpUser** [comment]
You simply define a variable and assign the incoming message to the variable as follows:

PythonShell.run(path.join(__dirname, "pyengine/view.py"), null, function (err,result) {
  if (err) throw err;
  console.log('finished');
  console.log(result)
  let value = result;

  //write code to use the value below, e.g

  //1. numeric value type
  let valueTypeOne = isNaN(parseFloat(result));
  if(valueTypeOne === true)
  {
    var testValue = value * 10:
  }
  
  //2. string value type
  let valueTypeTwo = typeof(JSON.parse(message)) === "string";
  if(valueTypeTwo === true)
  {
    var testValue = value + "test_message";
  }
 
  //3. Array value type
   valueTypeThree = Array.isArray(JSON.parse(JSON.parse(JSON.stringify(message))));
   if(valueTypeThree === true)
  {
    console.log(value);
    //or some other array operation
  }

  //4. etc...



});

**Comment by Almenon** [comment]
No response, closing.
