### ISSUE TITLE
No module named 'encodings'

### ISSUE THREAD

**Issue by doverradio** [extrabacon/python-shell#196]
Hello, I am trying to get python-shell to run one of my python scripts for the first time and I constantly get this error:

```
PythonShellError: Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```

How can I solve this?

**Comment by Almenon** [comment]
Are you able to run the python script with `python` without error? What's the output of `which python`?

**Comment by doverradio** [comment]
>>Are you able to run the python script with python without error?  
Yes

>> What's the output of which python?
I'm on windows 10 so I ran "whereis python" to obtain this location for python:
C:\ProgramData\Anaconda3\python.exe

**Comment by remcova** [comment]
@doverradio Did you find a solution for this? I have the exact same issue. I embedded Python in my Electron application and the module Encoding is present but still it can't find it. So it's probably looking in the wrong path but I don't know how to fix this.

**Comment by doverradio** [comment]
@remcova no I haven't found yet.  I'm still waiting for creator's response.  If only I could solve this, it would finish my project.

**Comment by remcova** [comment]
@doverradio Ah okay, same for me. If I solve this my project is finished too. I will let you know when I solve it.

**Comment by remcova** [comment]
@doverradio I solved it finally, I discovered that I was just missing the codecs.py file which should be present in the directory called "Lib". I thought that everything was present in the encodings directory itself but apparently not.

**Comment by doverradio** [comment]
@remcova that's fantastic!  However, where can I find codecs.py?  I checked in this repository but I didn't find here.  Can you post said file and filepath for the benefit of all?

**Comment by remcova** [comment]
@doverradio If you don't have the file, you can download it from here https://github.com/python/cpython/blob/3.8/Lib/codecs.py and place it manually in the Lib directory of Python. 

So make sure the module/directory called encodings is also present in your python "Lib" directory.

**Comment by doverradio** [comment]
@remcova YOU WIN THE INTERNET!  THANK YOU!

**Comment by Almenon** [comment]
Thanks @remcova :)

**Comment by remcova** [comment]
@doverradio @Almenon no problem! :)
