### ISSUE TITLE
Output should be accessible even when the script errors

### ISSUE THREAD

**Issue by TiraO** [extrabacon/python-shell#199]
https://github.com/extrabacon/python-shell/blob/968c651d2dcf92be7969927da07fbfc4794155aa/index.ts#L284

For debugging failures, it's very useful to have the rest of the output from the python code, not just the stacktrace.

**Comment by Almenon** [comment]
what exactly do you mean when you say output? Can you provide an example of expected result / actual result please?

**Comment by Almenon** [comment]
No response in months, closing.

**Comment by TiraO** [comment]
@Almenon My suggestion would be 
```javascript
if (err) return callback(err, output); 
```
For example:

```python
print('hello world')
raise Exception('goodbye world')
```

I would expect `callback` to be called with both the "goodbye world" error, and the "hello world" output.
