### ISSUE TITLE
Exchanging text data between Node and Python exists a small problem

### ISSUE THREAD

**Issue by silenceck** [extrabacon/python-shell#201]
###  test.js
```js
let {PythonShell} = require('python-shell');
let pyshell = new PythonShell('python/test.py');
pyshell.send("hello");
pyshell.on('message', function (message) {
  console.log(message);
});
```
###  test.py
```python
import json,sys

if __name__ == '__main__':   
    s = sys.stdin.read()
    print(s)
```
in this way,  console can print hello. but when i add { mode: 'text '} into the PythonShell constructor as below 
###  test.js
```
let {PythonShell} = require('python-shell');
let pyshell = new PythonShell('python/test.py', { mode: 'text '});
pyshell.send("hello");
pyshell.on('message', function (message) {
  console.log(message);
});
```
console dosen't print hello, it doesn't work.

**Comment by abdulahkam** [comment]
in test.py, you can add sys.stdout.flush()  after print() like this :

### test.py
`import json,sys

if __name__ == '__main__':   
    s = sys.stdin.read()
    print(s)
    sys.stdout.flush()  

`
