### ISSUE TITLE
spawn is not a function

### ISSUE THREAD

**Issue by hotwa** [extrabacon/python-shell#204]
My programming environment:
VScode
node.js  v12.14.0
vue-cli   4.X
and some plugin(electron-builder,vuetify)

![image](https://user-images.githubusercontent.com/49749136/71919180-fc9e4700-31be-11ea-99ac-c1cfcc418479.png)

> child_process_1.spawn is not a function

when I face this proble,first of all,I try to fix by myself. I found that in es6 value different from function. so, I changed like this:(in my test.js file)

```
let foo1 = PythonShell.run('./py/my_script.py', null, function (err) {
    if (err) throw err;
    console.log('finished');
});

function foo() {
    console.log("there is test.js,welcome!");
}

var a = 'my name is xiaoming';
export { foo, a, foo1 }
```
I ensured my es6 grammer.

then I try to do something python code in the my_script.py, which print("hello python!")
I get this picture.
I found this problem. 
then fond [this](https://stackoverflow.com/questions/42529261/uncaught-in-promise-typeerror-spawn-is-not-a-function)

> Spawn is a construct of nodejs. React as a framework does not have the method. This library is to be used in server side (nodejs). You can expose a http api which can be triggered via react. The http api can then trigger the library in nodejs server.

I know Spawn can't run in Vue-cli without nodejs.
Is there some ways to use Spawn in vue.js?  
I need nodejs run in client and invoke python script.

**Comment by Almenon** [comment]
No, you need node for this library. The browser does not have python built-in.
