### ISSUE TITLE
Supported Python Versions Inquiry

### ISSUE THREAD

**Issue by dfirence** [extrabacon/python-shell#205]
Hi Greetings

Thank you for making this awesome integration.  I have a need for using Python 3.6.6

Does this package support that version of Python?

If so, how would I point the node python-shell to execute a specific interpreter to ensure I am not going to run Python 2?

**Comment by Almenon** [comment]
Yes. If you're on windows point to `python`, if you're on mac/linux point to `python3`

**Comment by Almenon** [comment]
Note that on windows you need to install python first.
