### ISSUE TITLE
Buffer appears to be duplicated

### ISSUE THREAD

**Issue by DoctorTone** [extrabacon/python-shell#210]
Hi, I'm seeing a duplication of the data that I send to my python script from my node app.
I'm keeping the stream open and sending data at various points.

A summary of the code:

node:

```
const options = {
    mode: "json",
    pythonPath: process.env.PYTHON_PATH,
    scriptPath: "./myPath"
};
```
`let pythonShell = new python.PythonShell("myScript.py", options);`

`pythonShell.send([{"Person": "Someone"}]);`

Then:

```
this.pythonShell.on("message", function(results) {
	// Print any messages
	console.log(results);
        return;
});
```
Python:

```
import sys
import json

while True:
	line = sys.stdin.readline()
	command = line.split('\n')[0]
	command = json.loads(line)
	print(json.dumps(command))
	sys.stdout.flush()
```
First time through it prints the correct message.

[{"Person": "Someone"}]

Then on each subsequent send I get the mesage plus the previous message, i..e after sending twice I get 

[{"Person": "Someone"}]
[{"Person": "Someone"}]

and so on.

Could someone please shed some light on what I may be doing incorrectly?
I've tried from windows and ubuntu, I've tried using unbuffered input, I've tried flushing the input buffer but the results are always the same. Thanks.

**Comment by DoctorTone** [comment]
Converted code to use promises with async/await and it's all fine now!!

**Comment by DoctorTone** [comment]
Actually this was down to creating a new message listener after each send, thereby triggering multiple listeners whenever a message was recieved. Fixed by only listening for each event once before removing the listener.

**Comment by Miraj50** [comment]
@DoctorTone I am stuck in this situation too. Could you please tell me how you resolved it. 

For me, I wish to run the python script when a button is clicked. So, I have a function ("func"), which is called when the button is clicked. And here is the code:

```
const { PythonShell } = require('python-shell')
PythonShell.defaultOptions = { scriptPath: '/path/to/python/script/'};

function func() {
    var data = document.getElementById("someID").value
    let pyshell = new PythonShell('pythonfile.py')
    pyshell.send(data)
    pyshell.on('message', function (message) {
        console.log(message)
    })
    pyshell.end(function (err, code, signal) {
        if (err) throw err;
        console.log('The exit code was: ' + code);
        console.log('The exit signal was: ' + signal);
        console.log('finished');
    });
}
```
It does nothing when I click the button once, but on clicking the button twice, I get the output from the python file twice on the console.
This is the python file.

```
import sys
data = sys.stdin.readlines()
print(data)
sys.stdout.flush()
```
