### ISSUE TITLE
buffered python io

### ISSUE THREAD

**Issue by cojua8** [extrabacon/python-shell#218]
I'm working on a ui which has a progress bar, and my python script prints the progress in each iteration:
```python
import time
n = 25
for i in range(n):
    time.sleep(0.1)
    print(i, flush=True)
```

the javascript code I use is this:

```js
let pyshell = new PythonShell('script.py', {pythonOptions: ['-u']});

pyshell.on('message', function (message) {
    console.log(message)
    $('.progress > .progress-bar').attr('style', 'width:' + message + '%')
}
```

I think the code is ok, but all the values of console.log are printed to console after the script is finished, and the same happens to the progress bar, it does not have intermediate values.

**Comment by Almenon** [comment]
pythonOptions needs to be an array of strings, like so:

`pythonOptions: ['-u']`

**Comment by cojua8** [comment]
Oh yeah, it's a typo
