### ISSUE TITLE
Windows 10 code migrate to Ubuntu 8 CLI throwing [ERR_STREAM_DESTROYED]

### ISSUE THREAD

**Issue by XzibitGG** [extrabacon/python-shell#219]
### Issue
Our program is set up to handle requests sent by a client and then port a message to a python console using python-shell, which then sends back a response with the console output. 
Full relevant file can be found [here](https://gist.github.com/XzibitGG/4f1305319248bc45337f80a23d98efd7). However, looking at the relevant piece of code:

```typescript
      async spawnTerminal(){

      Chatbot.responseList = []

      Chatbot.responseOpius =  new PythonShell(__dirname + '/../../src/chatbotAPI/chatbot.py', { mode: 'text'})
      Chatbot.responseOpius.on('message', function (response : any) {
          if (Chatbot.responseList.length != 0){
              let sendTo = Chatbot.responseList.shift()
              sendTo.res.status(200).send(JSON.stringify(response.replace('>', '')))
          }
      })
    }
```

Now, this method is called once on startup. When running this setup on win 10, we receive the intended behavior, that is, another python terminal popups and the client is able to send requests and receive a response after the terminal listener is triggered. However, moving the exact same setup onto our servers, running Ubuntu 8 (CLI), the same code throws the following error:

![unknown 1](https://user-images.githubusercontent.com/27208624/83331469-a6609c00-a264-11ea-9513-059ada9806c5.png)

### Possible Cause
Again as stated, the EXACT same setup running off Win 10 works but not on Ubunutu 8. Looking at the error message, it seems as if the listener to trying to read from a terminal that doesn't exist. This could be due to the fact that maybe our server is closing all terminal popups. However, from my knowledge, python-shell restarts the terminal if it is closed resulting in a error being spammed into our logs which is not the case. Also, only difference other than that I can see would be missing dependencies, and hence, this issue.

**Comment by Almenon** [comment]
Can you post your Python code please

**Comment by XzibitGG** [comment]
Python code: https://gist.github.com/XzibitGG/354ccf463b3cc514962f594c6824c538
The ``chatbot()`` method is what's in charge of handling the input and writing to stdout.

**Comment by Almenon** [comment]
I'm guessing that a send is happening after the script completes but because the process is done it has a error when sending

**Comment by Almenon** [comment]
Maybe on Ubuntu the script completes faster than on Windows which is why you run into this?

**Comment by Almenon** [comment]
You can either restart the process or keep the process running in a loop listening to stdin or not write after script completion.

**Comment by XzibitGG** [comment]
Correct me if i'm wrong, but doesn't
`
       Chatbot.responseOpius.on('message', function (response : any) {
       })
`
Keep the process running in a loop while listening to stdin? Restarting the process is not ideal since it takes a while to load up the tensorflow model.

**Comment by Almenon** [comment]
I suppose my guess was wrong then. If the Python code is in a while true clause it shouldn't exit unless it is an error. And if there was a error presumably you would see it in the logs. I'm not sure why this is happening 🤔.

Btw Python-shell doesn't do any automatic restarting of a process or keep the process running. It's up to the process whether to keep running or not.

**Comment by Almenon** [comment]
Is your project open source by any chance? It would be helpful if I could see the full code.

**Comment by XzibitGG** [comment]
Yeah python code: https://github.com/XzibitGG/chatbot-rnn (chatbot.py being main)

Our JS project unfortunately is not. However, the only class that handles the PythonShell is this gist i provided, found here : https://gist.github.com/XzibitGG/4f1305319248bc45337f80a23d98efd7

If you wanna take a look here. Is it possible that since it is CLI is can't "show" the python terminal since there is no GUI support like on win 10?

**Comment by Almenon** [comment]
> Ubuntu 8

Do you mean to say ubuntu 18? Cause ubuntu 8 [is about a decade old](https://wiki.ubuntu.com/Releases), it must have security vulnerabilities up the wazoo. I would highly _highly_ recommend updating.

> Looking at the error message, it seems as if the listener to trying to read from a terminal that doesn't exist. 

The error message is with writing, not with reading.

> If you wanna take a look here. Is it possible that since it is CLI is can't "show" the python terminal since there is no GUI support like on win 10?

Python-shell just launches either `py` on windows or `python3` on other OS's, it doesn't try to launch a GUI terminal. No idea why that's happening.

**Comment by XzibitGG** [comment]
Ah, my apologies, yes, we're on ubunutu 18. Is there any other troubleshooting steps we can perform to narrow down the error?

**Comment by Almenon** [comment]
Yeah, you can debug your code. I would suggest placing a breakpoint at chatbot.js line 48 and stepping in. Take a look at the stream and check if it's closed. If it is closed you can either find out why and fix it if it should be open or you can add a conditional to not write if the stream is closed.

**Comment by XzibitGG** [comment]
Alright thanks! Will reply once we find the issue if you'd like to know, or you can close the thread.
