### ISSUE TITLE
error executing python 

### ISSUE THREAD

**Issue by pardhapi** [extrabacon/python-shell#22]
test.js file content:
var PythonShell = require('python-shell'); //external package
PythonShell.run('HelloWorld.py');

HelloWorld.py has following statement
print "Hello World"

When executing "node test.js" I'm getting following error. Any help is appreciated.

/home/pi/node_modules/python-shell/index.js:149
return callback(null, output.length ? output : null);
           ^
TypeError: undefined is not a function
    at null._endCallback (/home/pi/node_modules/python-shell/index.js:149:16)
    at ChildProcess.<anonymous> (/home/pi/node_modules/python-shell/index.js:99:35)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

**Comment by bruno-oliveira** [comment]
Have you read the documentation?

The "result" of the execution of a Python program is saved in a special variable called result...

So, on your server side code, when running the Python program, this should be done:
```javascript
PythonShell.run('teste.py',{ args: [some_arg]}, function (err, results) {
                if (err) throw err;
                // results is an array consisting of messages collected during execution
                console.log('results: %j', results);
```

On this example code, the program teste.py receives one command line argument and, after execution, two things might happen:

1. It is successful: the program ends correctly in Python: all the "results" (aka print statements in Python) are saved in a variable that can be used in JS called result.

2. Error: it throws an error.

**Comment by extrabacon** [comment]
The error you get comes from the missing callback argument. This argument is required (we could do a better validating those arguments).

```js
PythonShell.run('HelloWorld.py', myCallback);
```

**Comment by dolanmiu** [comment]
yes, i feel that the callback should be an optional parameter.

**Comment by GbalsaC** [comment]
@extrabacon 
This should be closed, passively calling a python script without giving a callback has no added value.

**Comment by dolanmiu** [comment]
@GbalsaC please elaborate why calling a python script without a callback has no added value?

I can think of many reasons why you would not need a callback

**Comment by GbalsaC** [comment]
Sure, in my personal (subjective view :) ) you can also pass an empty callback, however some integrations such as **Bluebird's Promisify** search for callbacks to create a promise wrapper.
While I'm not sure if this particular method would work with an optional parameter, it's in my opinion best to keep a callback parameter for good practice and there's no real effort in using a `(err, result)=>{}` parameter, even if you don't use it.

**Comment by Almenon** [comment]
closed based on @GbalsaC's reccomendation.  If someone raises a similar issue or another person chimes in agreeing with dolanmiu then this can be reopened.

**Comment by GermaVinsmoke** [comment]
`var pyshell = require('python-shell');

    pyshell.PythonShell.run('hello.py', null, function (err, results) {
        if (err) throw err;
        console.log('hello.py finished.');
        console.log('results', results);
    });
`
