### ISSUE TITLE
Execution time from python-shell is bigger than from console

### ISSUE THREAD

**Issue by skourta** [extrabacon/python-shell#221]
**The Question**:
The executions I have run using python shell from electron are taking a lot more time to execute than the results I get when I run the same scripts from the console. 
I just wanted to know the reason behind this slow up in the execution time, I am only timing the execution of the main function in the code, not the whole execution so the communication time is not included.
Thank you guys for any responses you might have!

**Any relevant python/javascript code:**
This is how I launch the script: 
```
await PythonShell.run(
        `${
          process.env.NODE_ENV === "development"
            ? "."
            : app.getAppPath("userData")
        }/Python/${this.args.name}.py`,
        {
          args: this.args.args
        },
        this.hadnleResults
      );
```
This is how I am timing the function in python:
```
    start_time = time.time()
    tour, cost = branchNbound(0, np.array(instance.data))
    end_time = time.time()

**Comment by Almenon** [comment]
Can you post the python script please?

**Comment by Almenon** [comment]
Also I'm not sure why this would happen, sorry

**Comment by skourta** [comment]
@Almenon Thank you for your response.
After further tests I believe that the cause might be CPU allocation, it is unrelated to the python-shell, because I tried to make a simple flask server to run my code and got the same long execution times. I will close the question.
