### ISSUE TITLE
Not getting response from Python backend on button click

### ISSUE THREAD

**Issue by Miraj50** [extrabacon/python-shell#222]
**The Question**:
I am making an electron app, which communicates with the python backend on clicking a button and logs the response in the console. The issue is that the result is logged twice every time the button is clicked twice. Nothing happens when the button is clicked once, although I have noticed (using ps aux) that a child process is indeed spawned. I have to use `pyshell.send()` because my data is large.

How can I fix this (get the result from python every single time the button is clicked)?

I made this [github gist](https://gist.github.com/Miraj50/f2391b92b4dba57fe7e1860bfa12565f) containing the relevant code. One just needs to run `npm install` and `npm start` to run the application. The python and js code are: 

**Any relevant python/javascript code:**
Python file:
```
import sys
data=""
for line in sys.stdin:
	data+=line.rstrip()
print(data)
sys.stdout.flush()
```
JS file: (the function is called using `<button onclick="get_weather()">Go!</button>`)
```
const { PythonShell } = require('python-shell')
function get_weather() {
    var data = "Cool Weather"
    let pyshell = new PythonShell('weather.py')
    pyshell.send(data)
    pyshell.on('message', function (message) {
        console.log(message+" HI")
    })
    pyshell.end(function (err, code, signal) {
        if (err) throw err;
        console.log(code + ' ' + signal);
    })
}
```

**Comment by Almenon** [comment]
```python
for line in sys.stdin:
	data+=line.rstrip()
```

The script will never get past this block as it will run forever. You're iterating over stdin but stdin doesn't have a end - input could theoretically come in forever, so each iteration the `for line in` waits for more input to come.

**Comment by Almenon** [comment]
Please test your python code first to make sure it works with command-line python. If it's working outside of python-shell but failing with python-shell, feel free to reopen.

**Comment by Miraj50** [comment]
Thank you for reaching out. It seems, the problem is solved if we use python's `input()` to take the data in from the python-shell. I had a doubt that it certainly has input length restrictions, but it seems to be working for now.
