### ISSUE TITLE
How to check if the program is running?

### ISSUE THREAD

**Issue by LeonardoRick** [extrabacon/python-shell#228]
Was the properly way to check if the PythonShell instance is currently running?

I'm currently using a third part library to check the PID number that I saved. Is there a better way to check that?

**Comment by Almenon** [comment]
By listening to the close eventl. If you don't receive it then it's still running.

**Comment by LeonardoRick** [comment]
It would be awesome to have a "IsRunning" property on the object. Also would be crazy if we could create this PythonShell instance before starting the program. Like create and then use a `program.strart()`. Just ideias, I don't even know if those things are possible. Thank's a lot!
