### ISSUE TITLE
Finish python child process when node server is finished on windows

### ISSUE THREAD

**Issue by LeonardoRick** [extrabacon/python-shell#232]
I think this is related to the OS architecture, but I really need the python program to end when my server finishes. On linux it works just fine because the child processes are related to the father. But on windows it seeems to keep runnnig after the server ends.

I couln't find if there's a way to force that over the library, but would be nice to have an option to keep the child process conected with tis father.

Let me know if theres any alternative or possiblity to do that.

Thank's a lot

**Comment by Almenon** [comment]
on [cleanup ](https://stackoverflow.com/questions/14031763/doing-a-cleanup-action-just-before-node-js-exits) you can `.kill()` the python script.

**Comment by LeonardoRick** [comment]
Yes, that's should work. Thanks. Closing here, but would be nice if it was possible to force this dependency on windows
