### ISSUE TITLE
Native accents being displayed wrongly on windows

### ISSUE THREAD

**Issue by LeonardoRick** [extrabacon/python-shell#234]
**Describe the bug**
If you print accented characters such as 'é', 'ê', 'ã', `python-shell` do not recognize it properly and return wrong characters such as: `�`

**Python code**
```python
import time
import sys

class Unbuffered(object):
    def __init__(self, stream):
        self.stream = stream

    def write(self, data):
        self.stream.write(data)
        self.stream.flush()

    def writelines(self, datas):
        self.stream.writelines(datas)
        self.stream.flush()

    def __getattr__(self, attr):
        return getattr(self.stream, attr)


sys.stdout = Unbuffered(sys.stdout)

x = 0
while True:
    print(f'{x}: This is a simple frase in portuguese.')
    print(f'{x}: Essa é uma frase simples em português.')
    time.sleep(5)
    x += 1
```

**Javascript code**
```javascript
const pyTeste = new PythonShell('teste.py', { scriptPath: 'C:\\Users\\leona\\Documents\\pythonScripts'});

pyTeste
  .on('message', (line: string) => {
    console.log(line);
  })
  .on('stderr', (std: string) => {
    console.log(std);
  })
  .on('error', err => {
    console.log('err');
    console.log(err);
  })
  .on('close', () => {
    console.log('Programa finalizado');
  });
```

**Expected behavior**
When I run python without `python-shell`, it prints:
```
0: This is a simple frase in portuguese.
0: Essa é uma frase simples em português.
```

**Actual behavior**
When I run the same scrypt by a `python-shell` instance, it prints:
```
0: This is a simple frase in portuguese.
0: Essa � uma frase simples em portugu�s.
```

**Other Information (please complete the following information):**
 - OS:  Windows10
 - Python Version: 3.8.7
 - Node Version: 12.15.0

**Comment by Almenon** [comment]
Python encoding has some wweeeeiirrrddd quirks. 

https://github.com/Almenon/AREPL-vscode/issues/329#issuecomment-617534633
^ I proposed setting a env var but I actually ended up solving it a different way:

https://github.com/Almenon/AREPL-backend/blob/0de3a2af876f7163a5e3ec34071e461e131bd400/python/arepl_python_evaluator.py#L321

You might not need to specify `line_buffering=True`

**Comment by Almenon** [comment]
I suppose I should probably set the `PYTHONIOENCODING` var for the user. The user is using python-shell for convenience, after all. People who want native functionality quirks included can use vanilla node.

**Comment by LeonardoRick** [comment]
I never manage python environtment variables,  but just

>  create a .env file in the root folder of your workspace with PYTHONIOENCODING=utf8

did not work for me. This is how my file looks like:

```
PYTHONIOENCODING=utf8
```

I also tried to load this file with `python-dotenv` with no success, even its apparently being loaded:

```python
import os
from dotenv import load_dotenv
load_dotenv()
print(os.environ.get('PYTHONIOENCODING'))
print('Frase simples em português')
```

output:
```
utf8
Frase simples em portugu�s
```

What am I missing?

**Comment by LeonardoRick** [comment]
I tried your other solution with this line: 
```
sys.stdout = TextIOWrapper(open(sys.stdout.fileno(), 'wb'), line_buffering=False, encoding='utf8')
```
but as you can see,  I was already changing my sys.stdout to a customized class, since I need this to be unbufered. I forced `line_buffering` to false, but the current behavior is wrong. It's not returning prints from the python scrypt. Is there a way to mixup this two features? ( unbuffered and utf8 encoding)

**Comment by Almenon** [comment]
> create a .env file in the root folder of your workspace with PYTHONIOENCODING=utf8

Sorry, that particular piece of advise was not literally meant for you, it was a fix specific to my [arepl](https://github.com/Almenon/AREPL-vscode) extension, as AREPL automatically reads in .env files in the root of the workspace.  In your case you can still use PYTHONIOENCODING but you will need to pass it in yourself.

> I also tried to load this file with python-dotenv with no success, even its apparently being loaded:
You almost got it right! Check out the documentation for [PYTONIOENCODING](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING)

*"If this is set before running the interpreter, it overrides the encoding used for stdin/stdout/stderr"*

It needs to be set before running the interpreter, but you were loading the env var after python was already running.  Instead try setting it in node, like so:

```typescript
import { Options, PythonShell } from './index'
const options: Options = {
    scriptPath: 'C:\\dev\\python-shell', env: {
        "PYTHONIOENCODING": "utf8"
    }
};
const pyTeste = new PythonShell('a.py', options);
pyTeste
    .on('message', (line: string) => {
        console.log(line);
    })
    .on('stderr', (std: string) => {
        console.log(std);
    })
    .on('error', err => {
        console.log('err');
        console.log(err);
    })
    .on('close', () => {
        console.log('Programa finalizado');
    });

console.log(`child process pid: ${pyTeste.childProcess.pid}`);
```

Note that the above is typescript, so I would recommend using [ts-node](https://github.com/TypeStrong/ts-node) to run it, or you can convert it into js if you really want.

**Comment by LeonardoRick** [comment]
This looks like a awesome feature and a easy way to setup environment variables! Really very intuitive.
