### ISSUE TITLE
.kill() do not work when { shell: true }

### ISSUE THREAD

**Issue by LeonardoRick** [extrabacon/python-shell#235]
**Describe the bug**
.kill() do not kill python process spawned when `{ shell: true }` is defined. I checked this [awesome thread on stackoverflow](https://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true), but I don't think this can be done here, since I'm not finding the PID of the spawned process. (`PythonShell` do not have a pid property)

**Python code**
```python
import time
import sys

class Unbuffered(object):
    def __init__(self, stream):
        self.stream = stream

    def write(self, data):
        self.stream.write(data)
        self.stream.flush()

    def writelines(self, datas):
        self.stream.writelines(datas)
        self.stream.flush()

    def __getattr__(self, attr):
        return getattr(self.stream, attr)


sys.stdout = Unbuffered(sys.stdout)

x = 1
while True:
    print(f'{x}: test if this could be killed with shell: true')
    time.sleep(10)
    x += 10

```

**Javascript code**
```javascript
const options = { scriptPath: 'C:\\users\\leona\\iq\\iq-websocket\\python\\botR', shell: true};

const pyTeste = new PythonShell('teste.py', options);

pyTeste
  .on('message', (line: string) => {
    console.log(line);
  })
  .on('stderr', (std: string) => {
    console.log(std);
  })
  .on('error', err => {
    console.log('err');
    console.log(err);
  })
  .on('close', () => {
    console.log('Programa finalizado');
  });

// this function do not work
setTimeout(() => {
  pyTeste.kill();
}, 10000);
```

**Expected behavior**
The library to check this situation and kill both the `shell` where the script is running and the script itself.

**Actual behavior**
The python program is never killed.

**Other Information (please complete the following information):**
 - OS: Windows10
 - Python Version 3.8.7
 - Node Version 12.15.0

**Comment by Almenon** [comment]
Errggg yeah good bug report. 

I've encountered this issue before. Killing with cross-platform compatibility is annoying.

Here's how I did it: https://github.com/Almenon/birdseye-vscode/blob/master/src/utilities.ts

> since I'm not finding the PID of the spawned process. (PythonShell do not have a pid property)

It doesn't have a pid property but the childProcess has a pid. Try `pyTeste.childProcess.pid`

**Comment by LeonardoRick** [comment]
I really missed the `.childProcess.pid`. This will help a lot.

I just used your function and changed the call I was making to 
```
setTimeout(() => {
  killAll(pyTeste.childProcess.pid);
}, 20000);
```
The  problem is that the program is exiting with an error: 
```
err
PythonShellError: process exited with code 1
    at terminateIfNeeded (C:\Users\leona\iq\iq-websocket\node_modules\python-shell\index.ts:193:27)
    at Socket.<anonymous> (C:\Users\leona\iq\iq-websocket\node_modules\python-shell\index.ts:164:17)
    at Socket.emit (events.js:228:7)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  executable: 'py',
  options: null,
  script: 'C:\\users\\leona\\iq\\iq-websocket\\python\\botR\\teste.py',
  args: null,
  exitCode: 1
}
```

Is there a way to kill it nicely with no errors?

**Comment by Almenon** [comment]
I would deregister the error handler right before you kill it, so the error is not logged.

**Comment by LeonardoRick** [comment]
But it sounds like this signal we are sending, are finishing the program in a abrupt way, isn't it? If not, why it's throwing and error and the implemented `kill()` method on the library don't? I think that maybe there's a way to send a gently signal to finish the program and we are almost achiving that.

**Comment by LeonardoRick** [comment]
@Almenon, since i'm not finding a way to kill it without throw the error, could you give me an example on how deregsiter only the error listener?

**Comment by Almenon** [comment]
> But it sounds like this signal we are sending, are finishing the program in a abrupt way, isn't it? If not, why it's throwing and error and the implemented kill() method on the library don't? I think that maybe there's a way to send a gently signal to finish the program and we are almost achiving that.

Not exactly. SIGTERM kills "gracefully" - the application has a chance to handle the signal before exiting. Your python code doesn't have any handlers so it simply exits with code 1. Example of handling signals: https://stackoverflow.com/questions/18499497/how-to-process-sigterm-signal-gracefully

> since i'm not finding a way to kill it without throw the error, could you give me an example on how deregsiter only the error listener?

I don't remember how to do it exactly. I suggest googling. I googled "node how to unregister handler" and found https://stackoverflow.com/a/23893949/6629672, which may be helpful
