### ISSUE TITLE
kill() do not trigger on('close') when using multiprocessing on linux

### ISSUE THREAD

**Issue by LeonardoRick** [extrabacon/python-shell#243]
**Describe the bug**
I'm using a class that relies on  multiprocessing to create a context manager that allow python programs to answer inputs from within. The problem is that when my program is inside this context manager, callinig python shell`kill()` method do not trigger `on('close')` handler. The program seems to stop running but maybe the `PythonShell` don't?

`program.terminated` actually returns true, but I guess something is missing and some trash is being left unhandled.

**Python code**
``` python

# innerstdin.py THE CLASS WITH MULTIPROCESSING
import sys
import multiprocessing

# context manager to write on stdin. use it as:
# stdin = InnerStdin()
# with stdin:
#    sys.stdin.write('now i can write on stdin and answer inputs if its asked for from within the program')
#
class InnerStdin:
    def __init__(self):
        self.queue = None
        self.real_stdin = sys.stdin
        self.relay_process = None

    def readline(self):
        return self.queue.get()  # when input() is called, it calls this function

    def writeline(self, s):
        self.queue.put(s)  # for input from elsewhere in the program

    def relay_stdin(self):
        my_stdin = open(0)  # this is a new process so it needs its own stdin
        try:
            while True:
                inp = my_stdin.readline()
                self.queue.put(inp)
        except KeyboardInterrupt:
            pass  # when killed, exit silently

    def __getstate__(self):
        #  This is called before pickling. and sys.stdin is not pickable
        self_dict = self.__dict__.copy()
        del self_dict['real_stdin']
        return self_dict

    def __enter__(self):
        # when entering the `with` block, start replace stdin with self and relay real stdin
        self.queue = multiprocessing.Queue()
        self.relay_process = multiprocessing.Process(target=self.relay_stdin)
        self.relay_process.start()
        sys.stdin = self

    def __exit__(self, exc_type=None, exc_val=None, exc_tb=None):
        # when exiting the `with` block, put stdin back and stop relaying
        sys.stdin = self.real_stdin

        self.relay_process.terminate()
        self.relay_process.join()

```

```python
# main.py THE CLASS THAT RUNS THE CODE

from iqbotrealtime.std.innerstdin import InnerStdin
import time


customStdin = InnerStdin()

with customStdin:
    while True:
        print('running...')
        time.sleep(1)

```
**Javascript code**
```javascript
    program = new PythonShell('main.py', pyOptions);
    program
      .on('message', (line: string) => {
       // ...
      })
      .on('stderr', (std: string) => {
       // ...
      })
      .on('error', err => {
       // ...
      })
      .on('close', () => {
        console.log('I\'m never called, but I should')
      });

      program.kill();
```

**Expected behavior**
the 'close' trigger should be called and the PythonShell instance should be ended.

**Actual behavior**
The program seems to stop run, but 'close' is never called and all cleanup cannot be made properly

**Other Information (please complete the following information):**
 - OS:
        Distributor ID:	Ubuntu
        Description:	Ubuntu 20.04.2 LTS
        Release:	20.04
        Codename:	focal

 - Python Version [3.8.5]
 - Node Version [v12.20.1]
 - Python Shell Version [3.0.0]

Thank's a lot for the amazing library!

**Comment by LeonardoRick** [comment]
@Almenon sorry disturbing you but I'm kinda in a rush... Do you have any ideia on how to make it work. Thanks for always helping me!

**Comment by Almenon** [comment]
I have work soon, but I can look into it later. In the meantime you can try passing in sigkill signal when calling kill and seeing if that helps.

**Comment by LeonardoRick** [comment]
@Almenon thanks a lot. I'll certainty try this solution

**Comment by LeonardoRick** [comment]
Just updating. I tried `program.kill('SIGKILL')` and it didn't worked.

I also changed this line to make my process daemonized:

```python
# innerstdin.py
self.relay_process = multiprocessing.Process(target=self.relay_stdin, daemon=True)
```

This second approach I was certain that was going to work, but sadly don't.

Something bad that I discovered is that the program is actually do not killed. I don't yet if both of them or only one is left  running, but openning my  Gnome System Monitor, it shows there after `program.kill()`

self.relay_process = multiprocessing.Process(target=self.relay_stdin, daemon=True)

![image](https://user-images.githubusercontent.com/17517057/118317623-acc84200-b4ce-11eb-8b56-6cf7d72475e7.png)

**Comment by LeonardoRick** [comment]
I found a solution!!

I don't know if this is the cleanest approach but I added a signal handler to be aweare of any `SIGTERM` sended to the program during execution of the context manager. If this signal is received, I call both `process.terminate()` and `process.join()`

Now I can guarantee that the process was being left running and that's why `on('close')` was never called. After this update, the `on('close')` handler started to be called again.

This is  how my context manager `__enter__` function looks like now:

```python
import signal
...

    def __enter__(self):
        # when entering the `with` block, start replace stdin with self and relay real stdin
        self.queue = multiprocessing.Queue()
        self.relay_process = multiprocessing.Process(target=self.relay_stdin, daemon=True) # ADDED DAEMON
        self.relay_process.start()
        signal.signal(signal.SIGTERM, self.finish_process) # ADDED SIGNAL HANDLER
        sys.stdin = self
```

And naturally, that's my `finish_process` function:

```python

    def finish_process(self, sig, frame):
        self.relay_process.terminate()
        self.relay_process.join()
``` 

Again, thanks for the amazing library that's helping me a LOT!

**Comment by Almenon** [comment]
Welcome :)
