### ISSUE TITLE
how use python-shell in vue?

### ISSUE THREAD

**Issue by Scat15** [extrabacon/python-shell#245]
First of all, thanks for making awesome package,
I want use python-shell in vue but 
![image](https://user-images.githubusercontent.com/37100990/120898416-4be9e080-c61a-11eb-87a5-f08a6f372caa.png)
then i found 
![image](https://user-images.githubusercontent.com/37100990/120898517-b26efe80-c61a-11eb-848e-41ea1cd87d32.png)
the demo code is
![image](https://user-images.githubusercontent.com/37100990/120898454-75a30780-c61a-11eb-8ea5-bf00cc249129.png)

**Comment by shivamsingha** [comment]
You can't run python itself in browser, unless you compile it to WASM or something.
You might wanna look somewhere else if you want to run python code in browser.

**Comment by Scat15** [comment]
> You can't run python itself in browser, unless you compile it to WASM or something.
> You might wanna look somewhere else if you want to run python code in browser.

oh thanks for reply，my opinion that use Electron,vue,python to build a win app but i found this problem,
so I need to find other way  to run python?

**Comment by shivamsingha** [comment]
I'm not familiar with electron. But generally you'd run python-shell in a node.js environment, where it can access the python binaries.  

I recommend you read this https://www.electronjs.org/docs/tutorial/using-native-node-modules
