### ISSUE TITLE
How can i set environment variables

### ISSUE THREAD

**Issue by camer314** [extrabacon/python-shell#247]
This may be a stupid question. Am just wondering how I can set environment variables such that my python scripts can use os.environ?

My setup is I am running from a nodejs web server inside a docker image. There is no conda environment or anything like that. I am currently setting environment variables in the dockerfile but obviously i would love to set them from my NodeJS prior to calling the script.

**Comment by camer314** [comment]
Sorry I just discovered the ENV setting in child_process.spawn which seems i can pass down in options.

**Comment by christopherpickering** [comment]
For someone else stumbling here... you can set easily:

```js
PythonShell.defaultOptions = {
    mode: 'text',
    env:{PYCHARM_HOSTED: 1}
  };
```

or in your task options

```js
import {PythonShell} from 'python-shell';

let options = {
  mode: 'text',
  env:{PYCHARM_HOSTED: 1}
};

PythonShell.runString('import os; print("PYCHARM_HOSTED" in os.environ)', null, function (err, result) {
  if (err) throw err;
  console.log(result)
  console.log('finished');
});
