### ISSUE TITLE
close event is emitted before all messages arrive

### ISSUE THREAD

**Issue by iamdoron** [extrabacon/python-shell#25]
Sometimes I get the close/end event before all messages arrive -  it happens rarely, but it happens, usually when I run many scripts in parallel.

here is an example:

```javascript
    const runningScript = new PythonShell("script.py", scriptOptions);
    runningScript.on('message', (message) => {
      console.log("message", message);
    });
    runningScript.end(() => {
      console.log("close"); // sometimes logged before messages arrive
      console.log(runningScript.terminated); // always logs true
    });
    runningScript.stdout.on('end', () => {
      console.log(runningScript.terminated); // always logs true
      console.log("stdout ended");
    })
```

My workaround for this is to listen to the stdout 'end' event for now

**Comment by extrabacon** [comment]
Listening to stdout ending is a good idea and would improve asynchronous events in a highly concurrent context. I will look into integrating this, or you can submit a pull request.

**Comment by iamdoron** [comment]
there's another related issue - you can (and I just verified it - it happens when you run many scripts in parallel) miss errors that come after the child_process 'exit' event
I think errors should be emitted after stderr has ended and the process exited

> Note that when the 'exit' event is triggered, child process stdio streams might still be open.

(https://nodejs.org/api/child_process.html#child_process_event_exit)
