### ISSUE TITLE
can I shuffle a js array?

### ISSUE THREAD

**Issue by zzzgit** [extrabacon/python-shell#265]
There is a js array, I want to call `Random.shuffle` to shuffle it. Is it possible?

**Comment by Almenon** [comment]
Yes, you could use this library to pass in the JS array to python, call Random.shuffle in the python code, and return it JS as the case may be. However, I would recommend just doing it in javascript: https://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array
