### ISSUE TITLE
Error using in conjunction with webpack

### ISSUE THREAD

**Issue by alexandersimoes** [extrabacon/python-shell#27]
Getting the following error:

```
ERROR in ./~/python-shell/index.js
Module not found: Error: Cannot resolve module 'child_process' in /path/to/file
 @ ./~/python-shell/index.js 4:12-36
```

**Comment by extrabacon** [comment]
Python shell is just an enhanced child process, and launching processes works only in Node, not the web. I don't think Webpack could supply an equivalent. See also: https://github.com/webpack/webpack/issues/744
