### ISSUE TITLE
PythonShell runs python with wrong architecture (on M1 mac)

### ISSUE THREAD

**Issue by ViggoV** [extrabacon/python-shell#276]
**Describe the bug**
When running `python3` on an arm64 Mac uses the correct architecture so that `>>> platform.machine()` prints `arm64`. However running as a script through PythonShell it runs as x86_64 architecture, ie. the output of `platform.machine()` is `x86_64`. This results in imports failing due to incompatible architecture when the packages are installed using the normal CLI. In my case `numpy` fails.

Node is running as expected as (`process.arch` prints `x64`)

**Python code**
Install numpy on an M1 Mac: `pip3 install numpy`

Run script through CLI and PythonShell, respectively
```
import platform
print(platform.machine())

import numpy
```

**Javascript code**
For reference/sanity check, run `console.log(process.arch)` through Node.

**Expected behavior**
PythonShell should run the executable as arm64, ie. `platform.machine()` should output `arm64` and imports should not fail.

**Actual behavior**
`platform.machine()` outputs `x86_64` and numpy fails to import with the following message:

```
PythonShellError: Original error was: dlopen(/Users/vef/Library/Python/3.9/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): tried: '/Users/vef/Library/Python/3.9/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/vef/Library/Python/3.9/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so' (no such file), '/Users/vef/Library/Python/3.9/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Other Information (please complete the following information):**
 - OS: MacOS Ventura 13.0.1
 - Python Version: 3.9
 - Node Version 14.19.3

**Comment by Almenon** [comment]
On Mac/Linux PythonShell just runs whatever python version/architecture `python3` on the terminal is linked to.

See https://github.com/extrabacon/python-shell#requirements

> First make sure you are able to run python3 (Mac/Linux) or python (Windows) from the terminal. If you are not then you might need to add it to the PATH. If you want to use a version of python not in the PATH you should specify options.pythonPath.

To run a different python version you can either change the python executable that appears first on your PATH or you can specify the path to a specific executable via `options.pythonPath`.

So, not a bug. Not sure how upgrading node fixed the issue for you, the version of node is unrelated to the version of python.
