### ISSUE TITLE
get returned values

### ISSUE THREAD

**Issue by wiiny** [extrabacon/python-shell#28]
Hi
I found a solution to return values : http://stackoverflow.com/questions/18231415/best-way-to-return-a-value-from-a-python-script
The best solution is : 
`import ...`
`def main():`
`    # calculcate stuff`
`    return [1,2,3]`
How can I do to get the returned values ?
Thanks for your help.

**Comment by extrabacon** [comment]
Returning values from a script works only if you import that script from another Python script. PythonShell runs your script in a separate process and can only communicate through stdin/stdout as well as the return code (which is usually reserved for errors).

To return that array, the simplest would be to set PythonShell into JSON mode and output the JSON-encoded array.

```python
import json
print json.dumps([1,2,3])
```
