### ISSUE TITLE
Does this package include python runtime in itself? 

### ISSUE THREAD

**Issue by AlexXi19** [extrabacon/python-shell#291]
I just wanted to confirm that this package does not depend on a system python dependency? I built an app with a node docker image without python and this package seemed to work fine so I was wondering if a system python dependency is not needed. 

Btw, great work on this package, the ease of use for starting a python process, passing in args, stdout handling etc. were done beautifully, thanks for you work!

**Comment by Almenon** [comment]
It does not include python. Your docker image happened to already have python included into it.

For example, if you used node:18
https://hub.docker.com/_/node
```
[18, 18-bullseye, 18.14, 18.14-bullseye, 18.14.2, 18.14.2-bullseye, hydrogen, hydrogen-bullseye, lts, lts-bullseye, lts-hydrogen](https://github.com/nodejs/docker-node/blob/cd7015f45666d2cd6e81f507ee362ca7ada1bfee/18/bullseye/Dockerfile)
```
`node:18` is equivalent to `node:18-bullseye`

"bullseye" is the codename for Debian 10: https://stackoverflow.com/questions/52083380/in-docker-image-names-what-is-the-difference-between-alpine-jessie-stretch-an

Debian and Ubuntu come with python pre-installed.

---

> Btw, great work on this package, the ease of use for starting a python process, passing in args, stdout handling etc. were done beautifully, thanks for you work!

Thanks! :)
