### ISSUE TITLE
PythonShell.runString is not a constructor

### ISSUE THREAD

**Issue by chrismatthieu** [extrabacon/python-shell#308]
I get the following error when running python strings:
PythonShell.runString is not a constructor

Ubuntu
NodeJS 22.3.0

```
        import {PythonShell} from 'python-shell';
     
	let pyShell = new PythonShell.runString(pythonScriptString, null);
	pyShell.on('error', function (err) {
		console.log('err', err);
	})
	pyShell.on('message', function(message) {
		console.log('message', message);
	})
	pyShell.on('end', function(err, code, signal) {
		if(err) throw err;
		console.log('exit code', code);
		console.log('exit signal', signal);
		console.log('finished');
	})
```

**Comment by daizhengqing** [comment]
not `new PythonShell.runString`，just `PythonShell.runString`

**Comment by Almenon** [comment]
see @daizhengqing's answer. 谢谢！

For more context, runString is not a constructor. but you are calling it like it is a constructor.

**Comment by chrismatthieu** [comment]
When I remove new from the initial line, I get a subsequent error saying:

error TypeError: pyShell.on is not a function
