### ISSUE TITLE
How does python receives the messages sent from node?

### ISSUE THREAD

**Issue by Jdash99** [extrabacon/python-shell#33]
This is the example for exchanging data between Node and Python:

```
var PythonShell = require('python-shell');
var pyshell = new PythonShell('my_script.py');

// sends a message to the Python script via stdin
pyshell.send('hello');

pyshell.on('message', function (message) {
  // received a message sent from the Python script (a simple "print" statement)
  console.log(message);
});

// end the input stream and allow the process to exit
pyshell.end(function (err) {
  if (err) throw err;
  console.log('finished');
});
```

Would kindly give me an example of the python part. How does python receives the message sent from node and do something with it?

**Comment by divinemanwah** [comment]
Please give an example if ever you already got your answer, I would like to know too.

**Comment by extrabacon** [comment]
Truly sorry for the delay. Messages are merely lines of text written to stdin/stdout. This is what makes python-shell so simple. In your Python script, just read from stdin to receive data. By default we split messages with carriage returns (\n), so every line written is considered a "message".

An example here: https://github.com/extrabacon/python-shell/blob/master/test/python/echo_text.py
