### ISSUE TITLE
Python subprocess returning a warning, reported as an error by python shell

### ISSUE THREAD

**Issue by marsmith** [extrabacon/python-shell#34]
First, thanks for the great work.  I'm using your python-shell often.

I'm running a sub command in my python script using `subprocess.call`.  The thing is this call is returning a warning, yet no matter what I do it is getting returned as an error to python-shell so that I can never see my results in the node script.

```
{ [Error: Warning 1: Value 14155551400 of field Shape_Area of feature 0 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 11811799300 of field Shape_Area of feature 1 not successfully written. Possibly due to too larger number with respect to field width
]
  executable: 'python',
  options: null,
  script: 'python/percentOverlay.py',
```

**Comment by extrabacon** [comment]
This warning is being written to stderr, which python-shell interprets as an error. A quick fix would be to parse the error message and simply ignore it if it starts with "Warning". This error being thrown does not interrupt execution in any way, it just reports it after execution has finished.

Another option would be to modify python-shell to optionally ignore content written to stderr and throw **only** when the exit code is not zero (https://github.com/extrabacon/python-shell/blob/master/index.js#L96).

**Comment by extrabacon** [comment]
Another option would be to redirect stderr output from `subprocess`, making sure it does not write to the stderr of the process being run by python-shell.

**Comment by haakenlid** [comment]
With standard cpython you can suppress some or all warning messages. You can probably fix this by setting the environment variable `PYTHONWARNINGS=ignore`
https://docs.python.org/3.4/using/cmdline.html?highlight=pythonwarnings#envvar-PYTHONWARNINGS

**Comment by Almenon** [comment]
I think this is resolved by https://github.com/extrabacon/python-shell/issues/130 - python shell can handle stderr now.
