### ISSUE TITLE
Passing mpi options

### ISSUE THREAD

**Issue by Spinman** [extrabacon/python-shell#35]
Hi, I'm trying to pass script parameters through python-shell but I'm not quite sure how I should set them. The setup I use can execute normal scripts and catch the responses fine but the command I'm trying to pass here seems a bit trickier. 

The commandline version I have tested and works is as follows: mpiexec -n 5 --hosts pi@raspi1, p2@raspi2 python MPI

Currently this is how I set the options: 
var options = {
mode: 'text',
pythonPath: 'usr/bin/python',
pythonOptions: ['mpiexec','-n 5','--hosts','pi@raspi1','p2@raspi2'],
scriptPath: 'MPI',
args: [null]
};
var pyshell = new PythonShell('testcalc.py',options);

I've tried to play with where the options belong but I'm not making any progress. 
Any thoughts?

Syntax for mpiexec: 
       mpiexec [global_args] local_args1 [: local_args2 [...]]
       mpiexec [global_args] -configfile <filename>

(Man pages for mpiexec http://linuxcommand.org/man_pages/mpiexec1.html)

**Comment by extrabacon** [comment]
I am unfamiliar with Python-based MPI, but if you can run the command as-is then you should use Node's `child_process` directly. 

`python-shell` starts python scripts with a python executable, using `child_process` underneath. Since your command is already an executable, there is no need to use python-shell and you can use `child_process` normally.

**Comment by Spinman** [comment]
I can use the chid_process.fork and send messages to it, but the problem is that it won't let me use the MPI functions. For that I could use child_process.exec, but that leaves me unable to send messages to it. Python-shell looked like a way to do both. I might be missing something here though.

**Comment by extrabacon** [comment]
True, `child_process.exec` does not give you access to stdin, it is meant for quick process execution (a command, some arguments, and the output). However, Node's `child_process.spawn` gives you full control over stdin, stdout and stderr. This is what `python-shell` uses underneath to communicate with Python processes.

As for `cross-spawn`, it seems like an improvement of `child_process.spawn` specifically for Windows.
