### ISSUE TITLE
How do I run the Python script before shell.end()

### ISSUE THREAD

**Issue by Larry850806** [extrabacon/python-shell#36]
This is my Node.js code:

``` javascript
var shell = new PythonShell('script.py');

shell.on('message', function(msg){
    console.log(msg);
});

shell.send('Hello');
shell.end();
```

And this is my Python script:

``` Python
tmp = raw_input()
print tmp
# just get input and output the same message
```

I want to send the message and get message from Python script.
But it always get message from Python after `shell.end()`
If I remove `shell.end()`, the Python script will never run.
And I will not get the message from Python script.
Is there any way to run script before `shell.end()`

**Comment by karlbateman** [comment]
Your `shell.send()` should be before the `shell.on()`.

**Comment by extrabacon** [comment]
Stdout is being buffered, meaning it accumulates data and sends it when the buffer is full. If your program does not write much, and never gets to fill the buffer, it will be flushed when the process terminates which is likely the case here.

You can explicitly flush the stdout buffer with `sys.stdout.flush()`. Note that buffering also applies to stdin if you need to write data from your Node app.
