### ISSUE TITLE
json non-whitespace problem

### ISSUE THREAD

**Issue by eldiablo62** [extrabacon/python-shell#4]
Hi 

i have a problem with your plugins.

// run a simple script
I have this script in node js
PythonShell.run('us.py', { mode: 'text'}, function (err, results) {
    console.log(results);
    response.send(results);
    response.end();
});

And this print value in my python script
print "%.2f" % distance1
print "%.2f" % distance2

The console.log of the nodejs script is : 
[ '42.38', '3.38' ]

And on the firefox web browser i obtain this error (firebug)
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 6 of the JSON data
json_data = jQuery.parseJSON($.trim(data));
	
I tried different thing but nothing good
change option (mode: json)
change my output on python 

I think the problem become because there is a space between [ and ' but i m not sure.

If you have a solution it will be very cool :)

**Comment by extrabacon** [comment]
Sorry for the delay... I think the data sent back to the browser has extra characters, or is wrongfully truncated. Can you inspect what is `data` in the browser and see if it matches your `console.log` statement?
