### ISSUE TITLE
Execute as root ?

### ISSUE THREAD

**Issue by todely** [extrabacon/python-shell#41]
Hi,

Is it possible to execute script from node.js as root?

Thanks

**Comment by extrabacon** [comment]
Python is launched as a child process. Launching your Node app as root should do the trick.

**Comment by todely** [comment]
I launch node with sudo and python script don't run.
It run perfect when i type sudo python xxx.py but not without sudo (dev mem acces for gpio)

**Comment by extrabacon** [comment]
You could also try setting `uid` on the child_process (0 for root). Just add `uid` to your python-shell options and it will be forwarded to child_process.

See: https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

**Comment by todely** [comment]
This is my cmd, where put the uid ?
 PythonShell.run('python/eclairage.py', function (err) {
 console.log("On Success");

**Comment by extrabacon** [comment]
Add options to your arguments. The `uid` options is not a python-shell option, so it gets forwarded to `child_process`. You could also experiment with other child_process options.

```js
PythonShell.run('python/eclairage.py', { uid: 0 }, function (err, results) {
  // all done
});
```
