### ISSUE TITLE
[Feature Request?] Ability to terminate python script

### ISSUE THREAD

**Issue by maarest** [extrabacon/python-shell#43]
Hi,

How can I terminate prematurely the python script that's executed through the shell? Or is it a feature request?

Thanks a lot!

**Comment by extrabacon** [comment]
You have access to the underlying `child_process` instance. After all, python-shell is nothing more than a wrapper over a child_process.

So, to kill your Python process:
```js
var python = new PythonShell('my_script.py');
// do stuff...
python.childProcess.kill();
```

https://nodejs.org/api/child_process.html#child_process_child_kill_signal
