### ISSUE TITLE
No wait response

### ISSUE THREAD

**Issue by jonatasfreitasv** [extrabacon/python-shell#44]
Have a possible to execute a Python script but no wait a response and no wait a python script finish ?

**Comment by extrabacon** [comment]
Sure, just create an instance normally and don't call `end`. However, quitting your node process will end your Python process as well. If you need to keep the Python process running after ending your node process, you can add the `detached` option. 

https://nodejs.org/api/child_process.html#child_process_options_detached

**Comment by jonatasfreitasv** [comment]
Thx @extrabacon !
