### ISSUE TITLE
End python-shell after a timeout? 

### ISSUE THREAD

**Issue by ax4** [extrabacon/python-shell#45]
Thanks so much for python-shell ! My web-app use python-shell as backend. It allows user to send their python code, run on my server, and return the stdout for them. 

However, sometimes, users may make mistakes, like writing an infinite loop. So I try to set a timeout, for example 5s, i.e. If a user's code cannot exit within 5s, the python-shell will force to end running his code. 

I wonder how this could be possible?

**Comment by extrabacon** [comment]
Thank you for you feedback! Timing out should be straightforward with a good old `setTimeout`.

```js
var PythonShell = require('python-shell');
var userScript = new PythonShell('some_script.py');

// kill the process after 5 seconds
var pythonKiller = setTimeout(function () {
  userScript.childProcess.kill();
}, 5000);

// closes stdin, allowing the process to end gracefully
userScript.end(function (err) {
  // process ended
  clearTimeout(pythonKiller);
}); 
```

**Comment by carlosen14** [comment]
Does this way launches an event?

`pyshell.on('error', function (error) {
});

pyshell.stdout.on('data', function (data) {
});

pyshell.on('message', function (message) {
});

pyshell.on('close', function (error) {
});`
