### ISSUE TITLE
yowsup-cli Error: process exited with code 1

### ISSUE THREAD

**Issue by sebastianet** [extrabacon/python-shell#46]
I am calling yowsup-cli from node using python-shell and it fails
If I call it from a Bash Shell, it works.
Any clue ?

Asking yowsup for help : >>> https://github.com/tgalal/yowsup/issues/1702

Nodejs code

===
app.post( '/enviar_msg_whatsapp/ParamTfNum=:req_tf_num', function (req, res) {

     var WhatsApp_Tf_Number = req.params.req_tf_num ;
     console.log( '>>> Menu enviar msg WhatsApp via python. Tf param is (' + WhatsApp_Tf_Number + '). ' ) ;

var python_options = {
  mode: 'text',
  pythonPath: '/usr/bin/python',
  pythonOptions: ['-u'],
  scriptPath: '/usr/local/bin',
  args: ['']
} ;

     PythonShell.run( 'yowsup-cli', python_options, function( err, results ) {
          if ( err ) throw err ;
          console.log( '(+) Snd WhatsApp Python results are (%j).', results ) ; // results is an array consisting of messages collected during execution
          var sndRC = String( results ) ;                           // convert to string

          szResultat = '+++ whatsapp msg sent. RC ('+ sndRC + ').' ;
          res.status( 200 ).send( szResultat ) ;
     } ) ; // run

} ) ; // enviar mensage whatsapp

==

Execution result :+1: 

===
>>> Menu enviar msg WhatsApp via python. Tf param is ("666777888").

/home/pi/semafor/1_sem.js:453
          if ( err ) throw err ;
                     ^

Error: process exited with code 1
    at terminateIfNeeded (/home/pi/semafor/node_modules/python-shell/index.js:100:23)
    at ChildProcess.<anonymous> (/home/pi/semafor/node_modules/python-shell/index.js:88:9)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
pi@raspberrypi-llovet:~/semafor $

===

Thanks.

===========================

Solved using

===
  args: [ 'demos',  '-c', '/usr/local/bin/mydetails',  '-s', '34666777888',  'Envio des el NODEJS' ]
===

**Comment by extrabacon** [comment]
So is it solved?

**Comment by sebastianet** [comment]
YES

I guess PythonShell.run() end up calling the UNIX system API,
than shall end up in calling "exec()",
which is known by problems managing the parameters.


I did not expect to receive "RC=1" when passing a "wrong" parameter.


Thanks.
