### ISSUE TITLE
Uncaught Error when sending data to and from script

### ISSUE THREAD

**Issue by AaronGillBraun** [extrabacon/python-shell#48]
I used the example given for sending and receiving data from a python script:

```python
var PythonShell = require('python-shell');
var pyshell = new PythonShell('my_script.py');
 
// sends a message to the Python script via stdin 
pyshell.send('hello');
 
pyshell.on('message', function (message) {
  // received a message sent from the Python script (a simple "print" statement) 
  console.log(message);
});
 
// end the input stream and allow the process to exit 
pyshell.end(function (err) {
  if (err) throw err;
  console.log('finished');
});
```

When i replace `my_script.py` with my python file name, the python script is in the same folder as the javascript file, when i run it, i get this error:

```
app.js:14 Uncaught Error: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'livestreamerApp.py': [Errno 2] No such file or directory
```

How do i fix this?

**Comment by extrabacon** [comment]
The script path is expected to be the current directory, it is not relative to your JS file. If you need to resolve from your JS file, join with `__dirname`.

https://github.com/extrabacon/python-shell/blob/master/index.js#L53

**Comment by AaronGillBraun** [comment]
Yeah thanks, I was reading through other issue and i found out I can't use absolute paths. I sorted it out but thanks a lot 👍
