### ISSUE TITLE
Use virtualenv to execute scripts

### ISSUE THREAD

**Issue by abdelrahman-elkady** [extrabacon/python-shell#49]
Is there any options to run the scripts inside a `virtualenv` context ? to be able to see the modules installed into the environment and  execute the binaries inside ?

**Comment by extrabacon** [comment]
This module will not help you setup the vitualenv, you need to set it first (either manually or using a shell script). You should then be able to point your Python binary to the one provided by your virtualenv. To change the path of the binary, simply set the `pythonPath` option.

**Comment by abdelrahman-elkady** [comment]
Yes, that's what I did, and I think it would work. Can't verify though because I got some `import`ing problems and I am not sure if this is because of virtualenv or because of module compatibility with python3. 

Anyways, thanks :))
