### ISSUE TITLE
How can I answer a python input() or raw_input()

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [extrabacon/python-shell#5]
I'm very new with node.js and I'm trying to make a web service for some Django command line tools.
In the python code of the utilities they use the input() for some questions.

For testing I've created a basic script:

**hello.py**

     print "Hello Mike!!"
     print "Hello Mike!!"
     print "Hello Mike!!"
     print "Hello Mike!!"
     print "Hello Mike!!"
     print "Hello Mike!!"
     print "Hello Mike!!"
     print "Hello Mike!!"
     x = input("Please")
     print "You're welcome %s" % x

I've copied some code of the demos an modified them a bit to check how they works:

    var PythonShell = require('python-shell');
    var options = {
        scriptPath: __dirname,
        mode: "text"
    }
    var pyshell = new PythonShell('hello.py', options);

    var i = 0;
    pyshell.on('message', function (message) {  
      console.log("Message #" + i, message);
      i++;
      if(message === "Please") {
        pyshell.send("Mike\n");
      }
    });

    pyshell.end(function (err) {
      if (err) {throw err;}
      console.log('finished');
    });

I'm getting some troubles with this, and this is the error stack that I'm receiving:

    $ node terminal.js                                                                                                                                      
    Message #0 Hello Mike!!
    Message #1 Hello Mike!!
    Message #2 Hello Mike!!
    Message #3 Hello Mike!!
    Message #4 Hello Mike!!
    Message #5 Hello Mike!!
    Message #6 Hello Mike!!
    Message #7 Hello Mike!!

    /Users/usuario/node/nodeTerminal/terminal.js:28
      if (err) {throw err;}
                      ^
    Error: EOFError: EOF when reading a line
        at PythonShell.parseError (/Users/usuario/node_modules/python-shell/index.js:131:17)
        at ChildProcess.<anonymous> (/Users/usuario/node_modules/python-shell/index.js:67:28)
        at ChildProcess.EventEmitter.emit (events.js:98:17)
        at Process.ChildProcess._handle.onexit (child_process.js:797:12)
        ----- Python Traceback -----
        File "/Users/usuario/node/nodeTerminal/hello.py", line 9, in <module>
          x = input("Please")

It would be nice to know how to make this work.
Thanks.

**Comment by extrabacon** [comment]
Node.js is asynchronous and this script closes the process too early. Your event handler is running asynchronously.

By the time you get to call `pyshell.send("Mike\n");`, the process has already been closed by calling `pyshell.end`. After calling `end`, you can no longer use `send` because the underlying stream has been closed.

You need to reorganize the code to call `end` asynchronously, after you're done sending any data. There are multiple libraries to assist you in writing asynchronous code, like [async](https://github.com/caolan/async).
