### ISSUE TITLE
How do I add the python libraries I need?

### ISSUE THREAD

**Issue by ingrid88** [extrabacon/python-shell#50]

**Comment by extrabacon** [comment]
Python shell simply runs your Python program like you would from the command line. Your Python script needs to import all required libraries by itself.

**Comment by ingrid88** [comment]
Ok - I see ... so if i want to put my node.js app on heroku i have to add appropriate build-packs that provide the python libraries i will need when i run the script...?

**Comment by extrabacon** [comment]
I think it would be much easier to use pip.
https://devcenter.heroku.com/articles/python-pip

You could add an `install` script in `package.json` to install your Python dependencies with pip. That would work pretty much everywhere Python+pip are available, and that includes Heroku.

**Comment by karlbateman** [comment]
Howdy,
Let's say you had the following nodejs application structure..

```
app.js
core/
content/
python/
...
```

An easy way to get what your after, is to use `virtualenv` and `pip`.. with that you can choose to bundle the environment with it's dependencies or make it part of your build step.

So to begin, you would create a virtualenv within your NodeJS app directory e.g.
```
virtualenv .env/ --python=python3
```

You will then need to source the activation script to activate the virtualenv e.g.
```
source ./env/bin/activate
```

then change to your python application directory and run the following..
```
pip install -r requirements.txt
```

At this stage, you just need to specify the path to the python binary within the virtualenv and all your dependancies will be available. For example..

```javascript
var options = {
  mode: 'text',
  pythonPath: '.env/bin/python3',
  pythonOptions: ['-u'],
  scriptPath: 'python/',
  args: ['value1', 'value2', 'value3']
};
```

If you are making this part of a build process then you will need to skip the step where you source the activate script and instead launch pip from within the virtualenv. For example

```
../.env/bin/pip3 -r requirements.txt
```
**Note** You will need to be in the directory of your python script.

That should be enough to get you going 😄

**Comment by NBNARADHYA** [comment]
> Howdy,
> Let's say you had the following nodejs application structure..
> 
> ```
> app.js
> core/
> content/
> python/
> ...
> ```
> 
> An easy way to get what your after, is to use `virtualenv` and `pip`.. with that you can choose to bundle the environment with it's dependencies or make it part of your build step.
> 
> So to begin, you would create a virtualenv within your NodeJS app directory e.g.
> 
> ```
> virtualenv .env/ --python=python3
> ```
> 
> You will then need to source the activation script to activate the virtualenv e.g.
> 
> ```
> source ./env/bin/activate
> ```
> 
> then change to your python application directory and run the following..
> 
> ```
> pip install -r requirements.txt
> ```
> 
> At this stage, you just need to specify the path to the python binary within the virtualenv and all your dependancies will be available. For example..
> 
> ```js
> var options = {
>   mode: 'text',
>   pythonPath: '.env/bin/python3',
>   pythonOptions: ['-u'],
>   scriptPath: 'python/',
>   args: ['value1', 'value2', 'value3']
> };
> ```
> 
> If you are making this part of a build process then you will need to skip the step where you source the activate script and instead launch pip from within the virtualenv. For example
> 
> ```
> ../.env/bin/pip3 -r requirements.txt
> ```
> 
> **Note** You will need to be in the directory of your python script.
> 
> That should be enough to get you going smile

I have a question..

nodejs is running on a normal environment. Do I need to activate the virtualenv and then run node app on the same ?
