### ISSUE TITLE
unable to get data from the script stdout

### ISSUE THREAD

**Issue by openStove** [extrabacon/python-shell#51]
Hi,

I try to write a simple script to read the data, like in your example, but nothing is happening
(I've checked and script is producing data on stdout...), what did I missed ?

`module.exports = function(RED) {
    function AccelerometerNode(config) {
        var PythonShell = require('python-shell');

```
    RED.nodes.createNode(this,config);
    var node = this;

    script="accelerometer.py";
    //scriptPath=__dirname
    args=["--sensor_update_rate","3"];


    var ls = new PythonShell(script,{ scriptPath: __dirname});

    ls.on('data', function (data) {
      node.log("data recieved : " + data)
    });

    ls.end(function (err) {
      if (err) throw err;
      node.log('finished');
    });

}
RED.nodes.registerType("accelerometer",AccelerometerNode);
```

}`

**Comment by extrabacon** [comment]
Basically it should work, as far as python-shell is concerned. I would need more info to provide further assistance. Can you provide a working code sample, including your Python script?

**Comment by haniawni** [comment]
Just seconding this issue, it's with both STDErr and STDOut. Example code is in this [gist](https://gist.github.com/haniawni/e70c66ecd5065ed4b6fcdbefeecf5e5f)

I'm not entirely certain, but i could've sworn earlier today I was getting stuff from stdOut and stdErr. Is it possible the python script is simply never getting processor time?

Problem persists through restart.

current Mac OSX, a few cores, etc, not that that should matter.
Using Python 2.7, hence the "from __future__ " line.

**Comment by haniawni** [comment]
Update: problem persists through uninstall/restart/reinstall song and dance

**Comment by extrabacon** [comment]
I'm sorry I am unable to recreate the issue. This Python code is not even valid with a stock Python installation (2.7.10). But this module is excessively simple and is a thin wrapper over node's `child_process`. Just make sure your Python script writes to stdout, which you can easily test from the terminal, and you should be good to go.

**Comment by mvelasco93** [comment]
Problem still exists. Cannot get back de stdout result to manipulate it. It only goes to console but when trying to assign it to a previously declared variable, it does nothing.

**Comment by bminixhofer** [comment]
Have you tried `sys.stderr.flush()` (or `sys.stdout.flush()`, depending on the case) after the `print` statement? I had the same problem and it works now.

**Comment by Almenon** [comment]
No response from OP - closing.
