### ISSUE TITLE
python: can't open file '../py/open-door.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dolanmiu** [extrabacon/python-shell#54]
For some reason, this command can't find the file `open-door.py`:

`python: can't open file '../py/open-door.py': [Errno 2] No such file or directory`

Here is the code I use to run the python script:

    PythonShell.run("open-door.py", { scriptPath: '../py' }, (err, result) => {
        if (err) {
            console.log("Script had an error: " + err);
            return;
        }

![screen shot 2016-09-16 at 00 24 45](https://cloud.githubusercontent.com/assets/2917613/18570690/12b20f24-7ba4-11e6-8b5c-d9836f8af9ec.png)
As you can see, `open-door.py` is inside the `/py` folder. 

The script calling `PythonShell.run(...` is inside the `/build` folder, (or `/ts` folder, `/ts` builds into `/build`)

I cannot see whats wrong! I am using OS X El Capitan. Could that be the reason?

Here is the project if anyone wants to try or check it out:
https://github.com/dolanmiu/Automated-Chicken-Coop-2

**Comment by extrabacon** [comment]
Scripts are resolved from the executable current directory (`./`). If you want to resolve scripts relative to your source code, use `__dirname` (https://nodejs.org/api/globals.html#globals_dirname).

**Comment by dolanmiu** [comment]
thanks! it worked perfectly
