### ISSUE TITLE
multiple .send() lead to 'write after end' error

### ISSUE THREAD

**Issue by kaYcee** [extrabacon/python-shell#56]
I am trying to send multiple commands to my python script, which is continuously listening in a thread. The first two commands - if chained - are received, but the third command, sent 3 seconds later, crashes the app with the following error:

> Error: write after end
>     at writeAfterEnd (_stream_writable.js:166:12)
>     at Socket.Writable.write (_stream_writable.js:217:5)
>     at Socket.write (net.js:651:40)
>     at PythonShell.send (/Users/.../node_modules/python-shell/index.js:205:16)
>     at Timeout.setTimeout (/Users/.../app.js:35:27)
>     at tryOnTimeout (timers.js:232:11)
>     at Timer.listOnTimeout (timers.js:202:5)

is any workaround known? thx!

node.js:

```
pyshell = new PythonShell('test.py', { mode: 'text' });
pyshell.send('CMD1').send('CMD2').end(function (err) {
    if (err) return done(err);
    done();
});

setTimeout(() => pyshell.send('CMD3').end(function (err) {
    if (err) return done(err);
    done();
}), 3000);
```

Python:

```
def listen():
   for line in sys.stdin:
      print("Received CMD " + line[:-1])
```

**Comment by extrabacon** [comment]
When you call `end`, it closes stdin, allowing your Python script to terminate. You can't send anything after `end` because that stream will be closed.

**Comment by JiunYiYang** [comment]
But is there a method to communicate between Python script and Nodejs without calling `end` ?
If I called `send` and `on` without `end`, it'll timeout during the `send` process...

Since if I need to send value to python and get python result back to nodejs multiple times, how will you suggest to revise my code below: 

```
var PythonShell = require('python-shell');

var options = {
    mode: 'text',
    pythonOptions: ['-u'],
    scriptPath: './../views',
};

var pyshell = new PythonShell('xxx.py', options);

router.get('/', function(req, res, next) {
  
  if (req.query.keywords != null) {
    pyshell.send(req.query.keywords);

    pyshell.on('message', function (message) {
      console.log(message);
      res.render('index', {
        result: message
      });
    });
    pyshell.end(function (err) {
      if (err){
        throw err;
      };
      console.log('finished');
    });
  }
  else {
    res.render('index', {
      result: ' '
    });
  }
});
```
