### ISSUE TITLE
Communication between Python & Node not work

### ISSUE THREAD

**Issue by DimTac** [extrabacon/python-shell#59]
Hi,

I have a problem with PythonShell and NodeJS.

I would like to execute a python script and get a value from user (with raw_input or sys.stdin.readline).
(I would like allows user enter the code in a popup in web-browser and Python-shell send it to Python script to continue.)

The script works fine when i execute them *_in the console mode *_ but when I use Pythonshell and Node.js, the script not waiting the user input and terminate with an error.

Can you help me to solve this issue ?

Thanks a lot.

Regards,
Dimitri
## launch.js

`
app.post('/launch_script', urlencodedParser, function (req, res) {
  if (!req.body) return res.sendStatus(400)
if(typeof(req.body.start_date) != 'undefined' && req.body.end_date != 'undefined' && req.body.property_uri != 'undefined' && sampleFile.name !='undefined')
  {
    var options = {
      mode: 'text',
      pythonOptions: ['-u'],
      args: [req.body.property_uri,req.body.start_date, req.body.end_date, 'files/data_url.csv']
    };

```
PythonShell.run('core.py', options, function (err, results) {
  if (err) throw err;

  pyshell.on('message', function (message) {
    // Send message in console
    console.log(message);
    //Send message in socket.io
    io.emit('logentry',message);
  });
});
```

  }`
## core.py

`def main(argv):
    # We clear prompt
    cls()
    args = argparser.parse_args()
    # get property_urir
    page = args.property_uri
    count_ok = 0
    flow = client.flow_from_clientsecrets(
    'client_secrets.json',
    scope=['https://www.googleapis.com/auth/webmasters.readonly'],
    redirect_uri='urn:ietf:wg:oauth:2.0:oob')

```
auth_uri = flow.step1_get_authorize_url()
print ("URL:"+auth_uri)

#Use stdin instead of raw_input beacause we use stdin in Python shell
print "Entrez le code recu : "
**auth_code = sys.stdin.readline()** #**This part not working when i execute the script with Python-Shelle, the script jump automatically to the next lines and fail**

credentials = flow.step2_exchange(auth_code)
http_auth = credentials.authorize(httplib2.Http())
service = build('webmasters','v3',http_auth)`
```

**Comment by Almenon** [comment]
Closing - issue is two years old and OP has probably solved issue or moved onto other stuff by now (OP correct me if I am wrong here)
