### ISSUE TITLE
Module not found: Error: Cannot resolve module 'child_process'

### ISSUE THREAD

**Issue by patomation** [extrabacon/python-shell#68]
Hi there I am trying to use Babble to load python shell like so:
```
import pythonShell from 'python-shell'
```
Then I get the following error:
```
Module not found: Error: Cannot resolve module 'child_process'
```
Any ideas? Isn't child process  a part of Node?

**Comment by extrabacon** [comment]
I have not tried to use python-shell with babel yet. Obviously, it should just work, as child_process is part of node and babel should have no trouble integrating with regular modules.

What does the transpiled code look like? Can you post a pre and post-babel example, along with your babel config?

**Comment by Almenon** [comment]
No response from OP in over a year. Closing.
