### ISSUE TITLE
Exit code 3221225794?

### ISSUE THREAD

**Issue by NamTThai** [extrabacon/python-shell#69]
I run python-shell in Windows 10. The Python script runs fine without nodejs. It's just a simple script that uses `numpy` and `gaussian_filters` from `scipy`. I got this error:

```
executable: "C:\Program Files\Anaconda2\python.exe"
exitCode: 3221225794
options: null
script: "python\gaussian-blur.py"
```

Any idea what might have happened?

**Comment by extrabacon** [comment]
Can you include the full exception details with message and stack trace?

**Comment by NamTThai** [comment]
That's the entire error I got from 

```
pyshell.end(function(err) {
console.log(err);
});
```

No stack trace was provided.

I'm using `iisnode` to integrate `nodejs` to Windows's `IIS`

**Comment by extrabacon** [comment]
OK this is weird, we should get an error with a stack trace (https://github.com/extrabacon/python-shell/blob/master/index.js#L102). This looks like we somehow get an empty object as the error. Can you reproduce by launching the node process yourself, without IIS?

**Comment by NamTThai** [comment]
Seems like an error from interaction between the module and IIS. It runs fine without IIS, no error, output as expected. Are you familiar with IIS?

**Comment by extrabacon** [comment]
In a previous life, yes. I never used node on Windows though. 

Looking at the source, we should have an error no matter what, so maybe the difference is the actual logging. Can you try `console.log(err.stack)` or `console.log(err.message)` and see if there's more to it?

**Comment by NamTThai** [comment]
Yes you're right there are more to it:

```
console.log(err.stack);
Error: process exited with code 3221225794
    at terminateIfNeeded (C:\Program Files\iisnode\cio-monitor\node_modules\python-shell\index.js:100:23)
    at ChildProcess.<anonymous> (C:\Program Files\iisnode\cio-monitor\node_modules\python-shell\index.js:88:9)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

console.log(err.message)
process exited with code 3221225794
```

And
```
{ [Error: Unable to register TclNotifier window class



This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

]
  executable: 'C:\\Program Files\\Anaconda2\\python.exe',
  options: null,
  script: 'python\\gaussian-blur.py',
  args: [ '2' ],
  exitCode: 3 }
Error: Unable to register TclNotifier window class


This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.


    at PythonShell.parseError (C:\Program Files\iisnode\cio-monitor\node_modules\python-shell\index.js:190:17)
    at terminateIfNeeded (C:\Program Files\iisnode\cio-monitor\node_modules\python-shell\index.js:98:28)
    at Socket.<anonymous> (C:\Program Files\iisnode\cio-monitor\node_modules\python-shell\index.js:78:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Unable to register TclNotifier window class
```

**Comment by extrabacon** [comment]
So, your Python process crashes unexpectedly. Interesting, but I doubt I can assist you further. Personally, I would simplify the Python script to run only the basics (maybe just a print statement) to confirm that the iisnode/python-shell combination can work. Then I would progressively incorporate third-party Python libraries and see where it goes.

**Comment by NamTThai** [comment]
Yeah still same error even with just the print statement. Thanks though! I'll reach out to `iisnode` owner maybe he knows what's going on.
