### ISSUE TITLE
PythonShell.send() not working on Windows (EOF issue?)

### ISSUE THREAD

**Issue by rabrahamkns** [extrabacon/python-shell#74]
Hi
I am running node on Windows, and trying to send(text). It seems as my python script may be stuck in reading from stdin. 
I then tried to run the example echo_text.py from a console, and it would not echo the input text. 
Only after I typed an EOF + enter (on Windows eof is ctrl+Z) it did echo the input text.
So if I run:
>>> python echo_text.py     <--- this is the script from python-shell\test\python folder
>>> test123
at this point nothing is echoed
only if I type these it works:
>>> python echo_text.py <--- run echo_text.py from the command console, script waitd for input
test123 <---- type test text + enter
^Z  <--- type ctrl+Z + enter
test123   <--- echoed as expected
I suspect this is the same reason send(data) is not working for me.

**Comment by rabrahamkns** [comment]
Code:
var PythonShell = require('../Server/node_modules/python-shell'),
    path = require('path');

function Pyexec(pyexecSettings) {
    this.pyexecSettings = pyexecSettings;

    var options = {
        mode: 'text',
        pythonOptions: ['-u'],
        scriptPath: path.join(__dirname, 'pyscripts')
    };

    this.pyshell  =  new PythonShell(pyexecSettings.pyScriptName, options);
    console.log('Pyexec: started script ' + pyexecSettings.pyScriptName);
}

Pyexec.prototype.send = function send(payload) {
    var self = this;
    self.pyshell.send(JSON.stringify(payload));
    self.pyshell.on('message', self.pyexecSettings.receive);
}

Pyexec.prototype.terminateScript= function terminateScript() {
    var self = this;
    if (self.pyshell) {
        self.pyshell.end(function (err) {
            if (err) throw err;
            console.log('Pyexec: end script ' + self.pyexecSettings.pyScriptName);
        });
        self.pyshell = null;
    }
}

module.exports = Pyexec;

**Comment by rabrahamkns** [comment]
Code:

```
var PythonShell = require('../Server/node_modules/python-shell'),
    path = require('path');

function Pyexec(pyexecSettings) {
    this.pyexecSettings = pyexecSettings;

    var options = {
        mode: 'text',
        pythonOptions: ['-u'],
        scriptPath: path.join(__dirname, 'pyscripts')
    };

    this.pyshell  =  new PythonShell(pyexecSettings.pyScriptName, options);
    console.log('Pyexec: started script ' + pyexecSettings.pyScriptName);
}

Pyexec.prototype.send = function send(payload) {
    var self = this;
    self.pyshell.send(JSON.stringify(payload));
    self.pyshell.on('message', self.pyexecSettings.receive);
}

Pyexec.prototype.terminateScript= function terminateScript() {
    var self = this;
    if (self.pyshell) {
        self.pyshell.end(function (err) {
            if (err) throw err;
            console.log('Pyexec: end script ' + self.pyexecSettings.pyScriptName);
        });
        self.pyshell = null;
    }
}

module.exports = Pyexec;
```

**Comment by rabrahamkns** [comment]
Test:
```

 var PyexecImport = require("../pyexec");

 var settings = {
     pyScriptName: 'Test_python-shell.py',
     receive: function(message) {
         console.log(message);
    }
 };

 var pyexec = new PyexecImport(settings);

 // send a message to the script
 var pyScriptMsg = {
 xlabel: 'x',
 ylabel: 'y',
data: [[1, 2, 3], [4, 5, 6]]
};

pyexec.send(pyScriptMsg);
```

**Comment by rabrahamkns** [comment]
After reading some more I now noticed I am not the first one who ran into this. Like you mentioned before the issue was Python's stdout was not being flushed, although I did call the Python script with the -u flag (for unbuffered). So I added a sys.stdout.flush call in my Python script, however, the code from the example did not work, but the code @punit-dato mentioned did:

```
line=' '
while line:
    line = sys.stdin.readline()
    print line
    sys.stdout.flush()
```

**Comment by extrabacon** [comment]
I wouldn't recommend using `-u` unless you want to output binary data, which you would use with the "binary" mode of python-shell (which is just the same as reading straight from the process streams).

Basically, both input and output streams are buffered, which means that you need to write enough data in order to receive it on the other end. Concerning EOF, it is closing the stream that is causing a flush. No need to do it explicitly, just allow your program to end normally and all should be well. For long-running tasks however, you need to flush explicitly, like `sys.stdout.flush` in Python.

**Comment by rabrahamkns** [comment]
got it, thanks for the help :+1:
