### ISSUE TITLE
Python-shell terminate the python script

### ISSUE THREAD

**Issue by akrami** [extrabacon/python-shell#75]
I'm working on a program that creates scrapy crawlers and crawls the web. I want to load these crawlers in my nodejs program. So the python file (runner.py) gets the crawler name as parameter and runs it
The problem is where the main python app creates a scrapy process and leaves itself, on this time the python-shell thinks that the script is finished and terminates the shell.
Is there a way I could run a script forever and don't end it?

**Comment by extrabacon** [comment]
Python shell simply wraps your python program with a child_process instance. It ends when the process is exited, which seems to be the case here. For long-running processes, you have to design your Python program this way, maybe by reading stdin indefinitely and exiting when you receive a SIGINT. But now your Python program is way more complex and you need to handle buffering carefully. 

Personally, I would design my app to run one isolated instance of scrapy crawler (1 Python process = 1 crawling task) and handle everything else from my Node app. This is a much simpler design, for which you get parallelization for free and do not need to worry about buffering. However you get some performance penalty by having multiple instances of Python.
