### ISSUE TITLE
Dynamically parsing output

### ISSUE THREAD

**Issue by jonesbra** [extrabacon/python-shell#78]
I used the functionality `shell.on('message', function(message){ console.log(message) })`, and I am able to collect all output of my script, and log it AFTER the script has finished. I would like to parse output as it is printed (dynamically) so that I may implement a progress bar in my electron app. Is this possible with python-shell?

**Comment by brucedjones** [comment]
I have noticed the same behaviour.

I found that you need to flush stdout from your python script to get the message event to fire. See this [SO answer](http://stackoverflow.com/a/10232330/1708869) and comments for more information. 

Some solutions are given [here](http://stackoverflow.com/questions/107705/disable-output-buffering). However, I have tested both the -u option and the PYTHONUNBUFFERED environment variable (on windows) without success.

I have found two workarounds which work with python-shell on windows, though neither are ideal.

1. Call sys.stdout.flush() whenever you want to fire the 'message' event
2. preppend the code in [this answer](http://stackoverflow.com/a/107717/1708869) to my script before passing it to python-shell

**Comment by MagnusPoppe** [comment]
This is actually not an error. Just you not setting the "pythonOptions: ['-u']," flag before running the script. 

``` JavaScript
      new PythonShell(scriptPath, {
        encoding: 'utf8',
        pythonPath: path.normalize(config().python),
        pythonOptions: ['-u'], // THIS ONE!!! 
        args:  args
      })
```

**Comment by brucedjones** [comment]
Magnus, please actually read my previous comment.

**Comment by Almenon** [comment]
The -u worked for me w/ python 3.6.0 on windows 10.  What version of python are you using @brucedjones ?

see https://github.com/Almenon/AREPL-backend/issues/6

**Comment by Almenon** [comment]
no response from anyone in the thread for a couple months.  Closing.
