### ISSUE TITLE
Receiving messages only after end

### ISSUE THREAD

**Issue by emmanuelgeoffray** [extrabacon/python-shell#8]
Hello,

I wrote this sample test code:
```
  1 var PythonShell = require('python-shell');
  2 var pyshell = new PythonShell('test_json.py', { mode: 'json'});
  3 
  4 
  5 pyshell.on('message', function (message) {
  6   // received a message sent from the Python script (a simple "print" statement) 
  7   console.log('received: ' + JSON.stringify(message));
  8   console.log('a: ' + message.command);
  9 }).on('error', function (err) {
 10   console.log(err);
 11 });
 12 
 13 // sends a message to the Python script via stdin 
 14 pyshell.send({ command: "do_stuff", args: [1, 2, 3] });
 15 
 16 pyshell.on('close', function () {
 17   console.log('close');
 18 });
```

And when i run it with `node app.js` it is stuck, it doesn't output anything.

On the other hand, if I add 
```
 22   pyshell.end(function (err) {
 23     if (err) throw err;
 24     console.log('finished');
 25   });}
```

I receive all the messages.

I don't get it. Why do I need to end the python script to get the messages?
I thought python-shell enabled live communication between nodejs and python script.

Am I wrong?
Thank you for you reply,
Emmanuel

PS: python script

```
  1 import sys, json
  2 
  3 # simple JSON echo script
  4 for line in sys.stdin:
  5   message = json.loads(line)
  6   print json.dumps(message)
  7   if message['command'] == 'do_stuff':
  8     message['command'] = 'do_it_yourself' 
  9     print json.dumps(message) 
 10  
```

**Comment by extrabacon** [comment]
Output is likely being buffered, meaning you did not send enough data to flush the buffer at least once. Closing stdin (by ending the process) forces the buffer to flush, causing your app to receive data. This is very common, you typically don't want to write every single byte as it would be too IO intensive.
