### ISSUE TITLE
Sending file buffer from node server to python script

### ISSUE THREAD

**Issue by crosofg** [extrabacon/python-shell#82]
How do I send a filestream to a python script which takes a file as argumetn? I dont want to save the file on the drive. How can that be done?

**Comment by extrabacon** [comment]
That script needs to accept file input via stdin, not a file path argument. From there you can pipe your Node readable stream to the Python process. If using python-shell, you will need to set the binary mode. Please note that you can accomplish this easily without python-shell, using a standard child_process to launch python instead.

**Comment by crosofg** [comment]
Thanks
