### ISSUE TITLE
Windows path in pythonPath

### ISSUE THREAD

**Issue by kanonenfutter** [extrabacon/python-shell#86]
I'm using python-shell on a Windows machine, but using a windows styled path pointing to Python 3.x throws this error:
```
Error: spawn C:\Users\<username>\AppData\Local\Programs\Python\Python36-32 ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

And this is how I created the path:
`var pypath = path.join(os.homedir() , 'AppData','Local','Programs','Python','Python36-32');`

So, what caused the error? I'm sure the folder exists. 

(Rewriting the python script in python 2.x is not an option because it depends on libraries written in python 3.x.)

**Comment by chesucr** [comment]
I think your path is incomplete, you must include the `python.exe` executable as well:

    var pypath = path.join(os.homedir() , 'AppData','Local','Programs','Python','Python36-32', 'python.exe');`

**Comment by Almenon** [comment]
Why not just include python in your PATH environment variable?  Also why is your python in your appdata folder?

**Comment by kanonenfutter** [comment]
Sorry for bothering you guys. The solution was embarrassingly simple. 
In my case, using the existing PATH variables does the job.

**Comment by edosssa** [comment]
Hi, I'm having a similar issue. It works when I run it from the command line but once I install it as a service using NSSM it fails to find the python executable. My guess is that the process started by NSSM doesn't include python in PATH. Any help or ideas would be greatly appreciated!
