### ISSUE TITLE
PythonShell.parseError - Error: ImportError: No module named site

### ISSUE THREAD

**Issue by PersistentlyHungry** [extrabacon/python-shell#88]
I'm getting this error when trying to execute the following code:

var pyshell = new PythonShell('my_script.py', {
        mode: 'json',
        pythonOptions: ['-u'],
        scriptPath: __dirname + '/core',
        args: ['message']
      });

Any ideas how to solve this?

**Comment by bttb66** [comment]
You need to write pythonPath at the options like this
 var option = {
            mode: 'text',
            pythonPath: '/usr/bin/python',
            pythonOptions: ['-u'],
            scriptPath: __dirname,
            args: ['message']
        };

**Comment by AsmaGargouri** [comment]
@bttb66 I tried this, it didn't work

**Comment by Almenon** [comment]
you have a problem with your python code.  If you still have the issue I would suggest asking on stackoverflow with a snippet of the python code that causes the issue.
