### ISSUE TITLE
Error: ImportError: No module named (module)

### ISSUE THREAD

**Issue by smakerdev** [extrabacon/python-shell#89]
my options is ..

"var options = {
  mode: 'json'
};"

Why does this error occur?

I'll run python tenserflow application in Node.js

**Comment by bttb66** [comment]
You need to write pythonPath at the options like this
var option = {
mode: 'text',
pythonPath: '/usr/bin/python',
pythonOptions: ['-u'],
scriptPath: __dirname,
args: ['message']
};

**Comment by Almenon** [comment]
no response from OP - closing
