### ISSUE TITLE
Sending json to node.js app from python script

### ISSUE THREAD

**Issue by datainvestor** [extrabacon/python-shell#98]
Hi I'm trying to send a json from python (a dataframe converted to json) to the node.js app

In js I just included simple python-shell lines that would send a variable from node to script.py, it runs and it sends the output back to node.
The thing is that instead of json Im getting strings. 

This is the node.js side
```
            var pyshell = new PythonShell('script2.py');
            pyshell.send(JSON.stringify(pyvar))
            pyshell.on('message', function (message) {
    // received a message sent from the Python script (a simple "print" statement)
            var jsondata = message
            console.log(typeof(jsondata));
            });

// end the input stream and allow the process to exit
            pyshell.end(function (err) {
             if (err){
                throw err;
                };
```

In python 
```

def read_in():
    lines = sys.stdin.readlines()
    # Since our input would only be having one line, parse our JSON data from that
    return json.loads(lines[0])
def main():
    lines = read_in()

    .....

    df=df.to_json
    print(df)
    
if __name__ == '__main__':
    main()

```
Now as I understood I can send the data from python by using print()? Or is there another way to send the output from python to node.js while saving its datatype (not converting to string)

**Comment by Almenon** [comment]
JSON can be a string.  You can take a string and convert it into JSON.  In javascript you can do this with JSON.parse(yourString).  Press f12 to open your dev tools and try it out:

```javascript
x = JSON.parse('{"a":5}')
```
