### ISSUE TITLE
Run a python function  from node?

### ISSUE THREAD

**Issue by tasoskakour** [extrabacon/python-shell#99]
Hello, first of all fantastic work!

Say that I have a function named hello(str) inside a python file named script.py

How can I only call this hello(str) function from node?

Thanks in advance!

**Comment by extrabacon** [comment]
Python shell launches Python scripts, just like you would from the command line. So you could create new a file, import your function and then simply call it.

**Comment by Lucky7Chess** [comment]
Sometimes you don't want to have the imports happen multiple times, like the import of Tensorflow takes a long time so running a function within a python script could be a needed feature.

**Comment by Almenon** [comment]
@Lucky7Chess I really don't see that feature ever happening.  If you want to only have imports happen once then just import at the start at the script and have a loop checking stdin to determine which function to call.  You can look at https://github.com/Almenon/AREPL-backend/blob/master/python/pythonEvaluator.py for an example
